import { sourceById } from '../sources/registry';import { extractArticle } from './extract';import { makeStoryPacket } from './story';import { embedText } from '../embedding';import { clusterArticle } from '../cluster';import { maybeResourceCandidate } from '../resources';import type { IngestMessage } from '../types';
const PAPUA=/papua|jayapura|sentani|cycloop|raja ampat|sorong|manokwari|nabire|merauke|timika|mimika|biak|wamena|puncak|nduga|intan jaya|yahukimo|deiyai|dogiyai|paniai|fakfak|kaimana|tambrauw|maybrat|arfak/i;
const canonical=(url:string)=>{try{const u=new URL(url);['utm_source','utm_medium','utm_campaign','utm_content','fbclid','gclid'].forEach(k=>u.searchParams.delete(k));u.hash='';return u.href.replace(/\/$/,'')}catch{return url}};
async function sha256(text:string){const bytes=new TextEncoder().encode(text.replace(/\s+/g,' ').trim());const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function processArticle(env:any,message:IngestMessage){
  const source=sourceById[message.sourceId];if(!source)return {skipped:'unknown source'};const incoming=canonical(message.url);let known:any=await env.DB.prepare(`SELECT id,status FROM articles WHERE canonical_url=?`).bind(incoming).first();if(known?.status==='clustered')return {skipped:'known'};
  const extracted=await extractArticle(message.url,source,env);if(!extracted)return {skipped:'extract'};extracted.canonicalUrl=canonical(extracted.canonicalUrl);if(extracted.canonicalUrl!==incoming){const canonicalKnown:any=await env.DB.prepare(`SELECT id,status FROM articles WHERE canonical_url=?`).bind(extracted.canonicalUrl).first();if(canonicalKnown?.status==='clustered')return {skipped:'known canonical'};known=canonicalKnown||known}
  if(source.scope==='mixed'&&!PAPUA.test(`${extracted.title} ${extracted.description} ${extracted.body.slice(0,9000)}`))return {skipped:'not-papua'};
  const fetched=new Date().toISOString();const hash=await sha256(extracted.body);extracted.contentHash=hash;const syndicated:any=await env.DB.prepare(`SELECT id FROM articles WHERE content_hash=? AND publisher_id<>? ORDER BY id LIMIT 1`).bind(hash,source.id).first();
  await env.DB.prepare(`INSERT INTO publishers(id,name,homepage,role,ownership,enabled,updated_at,priority,notes) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,homepage=excluded.homepage,role=excluded.role,ownership=excluded.ownership,enabled=excluded.enabled,updated_at=excluded.updated_at,priority=excluded.priority,notes=excluded.notes`).bind(source.id,source.name,source.homepage,source.role,source.ownership,source.enabled?1:0,fetched,source.priority||2,source.notes||null).run();
  let id:number;if(known?.id){id=Number(known.id);await env.DB.prepare(`UPDATE articles SET publisher_id=?,canonical_url=?,title=?,summary=?,body_excerpt=?,language=?,published_at=COALESCE(?,published_at),fetched_at=?,status='normalized',extraction_method=?,content_hash=?,syndicated_from_article_id=? WHERE id=?`).bind(source.id,extracted.canonicalUrl,extracted.title,extracted.description,extracted.body.slice(0,12000),extracted.language||source.language[0],extracted.publishedAt||message.publishedAt||null,fetched,extracted.extractionMethod||'fetch+fallback',hash,syndicated?.id||null,id).run()}else{const insert:any=await env.DB.prepare(`INSERT INTO articles(publisher_id,canonical_url,title,summary,body_excerpt,language,published_at,fetched_at,status,extraction_method,content_hash,syndicated_from_article_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(source.id,extracted.canonicalUrl,extracted.title,extracted.description,extracted.body.slice(0,12000),extracted.language||source.language[0],extracted.publishedAt||message.publishedAt||null,fetched,'normalized',extracted.extractionMethod||'fetch+fallback',hash,syndicated?.id||null).run();id=Number(insert.meta.last_row_id)}
  await env.ARCHIVE.put(`articles/${id}.txt`,extracted.body,{httpMetadata:{contentType:'text/plain; charset=utf-8'},customMetadata:{source:source.id,url:extracted.canonicalUrl,extraction:extracted.extractionMethod||'unknown'}});
  if(extracted.image)await env.DB.prepare(`INSERT OR IGNORE INTO image_candidates(article_id,url,source_url,credit,caption,rights_status,created_at) VALUES(?,?,?,?,?,?,?)`).bind(id,extracted.image.url,extracted.image.sourceUrl,extracted.image.credit||source.name,extracted.image.caption||null,'attributed_external',fetched).run();
  let packet:any=null;if(syndicated?.id){const prior:any=await env.DB.prepare(`SELECT * FROM story_packets WHERE article_id=?`).bind(syndicated.id).first();if(prior){const parse=(v:any)=>{try{return JSON.parse(String(v||'[]'))}catch{return[]}};packet={summary:prior.summary,key_points:parse(prior.key_points_json),what_changed:prior.what_changed||'',event_date:prior.event_date||extracted.publishedAt,places:parse(prior.places_json),people:parse(prior.people_json),organizations:parse(prior.organizations_json),topics:parse(prior.topics_json),issue_candidates:parse(prior.issue_candidates_json)}}}if(!packet)packet=await makeStoryPacket(env,extracted,source);await env.DB.prepare(`INSERT INTO story_packets(article_id,summary,key_points_json,what_changed,event_date,places_json,people_json,organizations_json,topics_json,issue_candidates_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(article_id) DO UPDATE SET summary=excluded.summary,key_points_json=excluded.key_points_json,what_changed=excluded.what_changed,event_date=excluded.event_date,places_json=excluded.places_json,people_json=excluded.people_json,organizations_json=excluded.organizations_json,topics_json=excluded.topics_json,issue_candidates_json=excluded.issue_candidates_json,created_at=excluded.created_at`).bind(id,packet.summary,JSON.stringify(packet.key_points),packet.what_changed,packet.event_date||null,JSON.stringify(packet.places),JSON.stringify(packet.people),JSON.stringify(packet.organizations),JSON.stringify(packet.topics),JSON.stringify(packet.issue_candidates),fetched).run();
  const embeddingInput=`${extracted.title}\n${packet.summary}\n${packet.key_points.join('\n')}\nPlaces: ${packet.places.join(', ')}\nOrganizations: ${packet.organizations.join(', ')}\n${extracted.body.slice(0,4500)}`;const vector=await embedText(env,embeddingInput);await env.ARTICLE_INDEX.upsert([{id:String(id),values:vector,metadata:{publisher:source.id,publishedAt:extracted.publishedAt||fetched,title:extracted.title}}]);
  await env.DB.prepare(`UPDATE articles SET status='embedded' WHERE id=?`).bind(id).run();const row=await env.DB.prepare(`SELECT * FROM articles WHERE id=?`).bind(id).first();const developmentId=await clusterArticle(env,row,vector);await maybeResourceCandidate(env,{...extracted,id,packet},source);await env.DB.prepare(`UPDATE articles SET status='clustered' WHERE id=?`).bind(id).run();return {id,developmentId,extraction:extracted.extractionMethod,syndicatedFrom:syndicated?.id||null};
}
