import { runChat } from '../llm';
import type { ExtractedArticle,SourceConfig,StoryPacket } from '../types';

const cleanArray=(value:any)=>Array.isArray(value)?value.map(String).map(v=>v.trim()).filter(Boolean).slice(0,16):[];
const confidence=(value:any)=>Math.max(0,Math.min(1,Number(value)||0));
export async function makeStoryPacket(env:any,article:ExtractedArticle,source:SourceConfig):Promise<StoryPacket>{
  const prompt=`Create a structured story packet for clustering and later editorial synthesis. Use only the supplied article. Do not infer motives or facts that are not stated. Decide whether this belongs on a publication specifically watching the western half of New Guinea / Indonesian-administered Papua and West Papua. Papua New Guinea or unrelated Indonesian stories are not relevant unless the article materially concerns West Papua/Papuan people/issues. Return JSON only with keys summary, key_points, what_changed, event_date, places, people, organizations, topics, issue_candidates, watch_relevance, watch_relevance_confidence, watch_desk. watch_desk must be one of environment, land, human_rights, politics, culture, regional, other.\n\nPublisher: ${source.name}\nRole: ${source.role}\nTitle: ${article.title}\nPublished: ${article.publishedAt||''}\nDescription: ${article.description}\nArticle:\n${article.body.slice(0,14000)}`;
  try{const raw=await runChat(env,[{role:'system',content:'Extract concrete facts conservatively. Keep names and place names as written. issue_candidates should be broad stable themes, not invented issue titles. Be strict on West Papua relevance.'},{role:'user',content:prompt}],'fast',980);const obj=JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0]||'{}');const desk=['environment','land','human_rights','politics','culture','regional','other'].includes(String(obj.watch_desk))?String(obj.watch_desk) as StoryPacket['watch_desk']:'other';return {summary:String(obj.summary||article.description).slice(0,1800),key_points:cleanArray(obj.key_points),what_changed:String(obj.what_changed||'').slice(0,1000),event_date:String(obj.event_date||article.publishedAt||'').slice(0,64)||undefined,places:cleanArray(obj.places),people:cleanArray(obj.people),organizations:cleanArray(obj.organizations),topics:cleanArray(obj.topics),issue_candidates:cleanArray(obj.issue_candidates),watch_relevance:obj.watch_relevance===true,watch_relevance_confidence:confidence(obj.watch_relevance_confidence),watch_desk:desk}}
  catch{return {summary:article.description,key_points:[],what_changed:'',event_date:article.publishedAt,places:[],people:[],organizations:[],topics:[],issue_candidates:[],watch_relevance:source.scope==='papua',watch_relevance_confidence:.35,watch_desk:'other'}}
}
