export const CRITIC_INSTRUCTION='Audit EACH Development independently against only its supplied evidence. Check support, attribution, headline overclaiming, every key point, syndication, geography/relevance, and whether its records are one bounded unfolding episode rather than merely the same topic. Directly connected stops, promises and reactions during an identified visit belong together; they are not a cluster_problem just because the actions differ. Different visits or unrelated events remain separate. A single credible local report can pass when clearly attributed. Never mix evidence between Development ids.';
import { runJson,isGatewayQuotaError,isMalformedOutputError,modelLabelFor,type ChatPurpose } from '../llm';
import { tryEmbedText } from '../embedding';
import { upsertDevelopmentSearch } from '../search';
import { rebuildDevelopmentKnowledge } from '../knowledge';
import { validatePartition } from './partition';

const arr=(v:any)=>{try{const x=JSON.parse(String(v||'[]'));return Array.isArray(x)?x.map(String):[]}catch{return[]}};
const text=(v:any,n:number)=>String(v||'').trim().slice(0,n);
const list=(v:any,n=12)=>Array.isArray(v)?v.map(String).map(x=>x.trim()).filter(Boolean).slice(0,n):[];
const MAX_LOGICAL_REVISIONS=4;
const MAX_EDITORIAL_BATCH=4;

const draftItem={type:'object',properties:{development_id:{type:'integer'},title_en:{type:'string'},summary_en:{type:'string'},title_id:{type:'string'},summary_id:{type:'string'},key_points_en:{type:'array',items:{type:'string'}},key_points_id:{type:'array',items:{type:'string'}},what_changed_en:{type:'string'},what_changed_id:{type:'string'},common_ground:{type:'array',items:{type:'string'}},source_notes:{type:'array',items:{type:'string'}},places:{type:'array',items:{type:'string'}},topics:{type:'array',items:{type:'string'}}},required:['development_id'],additionalProperties:true};
const draftBatchSchema={type:'object',properties:{items:{type:'array',items:draftItem}},required:['items'],additionalProperties:false};
const criticItem={type:'object',properties:{development_id:{type:'integer'},verdict:{type:'string',enum:['pass','revise']},unsupported_claims:{type:'array',items:{type:'string'}},framing_problems:{type:'array',items:{type:'string'}},cluster_problem:{type:'boolean'},relevance_problem:{type:'boolean'},note:{type:'string'}},required:['development_id'],additionalProperties:true};
export const criticBatchSchema={type:'object',properties:{items:{type:'array',items:criticItem}},required:['items'],additionalProperties:false};

async function loadItems(env:any,id:number){const rows:any=await env.DB.prepare(`SELECT a.id,a.title,a.summary,a.published_at,a.fetched_at,a.syndicated_from_article_id,a.canonical_url,p.id publisher_id,p.name publisher,p.role,sp.summary packet_summary,sp.key_points_json,sp.what_changed,sp.event_key,sp.action,sp.object,sp.places_json,sp.organizations_json,sp.topics_json,sp.issue_candidates_json,sp.watch_relevance,sp.watch_relevance_confidence,sp.item_type,sp.evidence_roles_json FROM development_articles da JOIN articles a ON a.id=da.article_id JOIN publishers p ON p.id=a.publisher_id LEFT JOIN story_packets sp ON sp.article_id=a.id WHERE da.development_id=? ORDER BY julianday(COALESCE(a.published_at,a.fetched_at)) DESC LIMIT 24`).bind(id).all();return rows.results||[]}

const contextFor=(items:any[])=>items.slice(0,24).map((r:any,i:number)=>`[S${i+1}] ${r.publisher} (${r.role})\nItem type: ${r.item_type||'unclassified'}\nEvidence roles: ${arr(r.evidence_roles_json).join(', ')||'unclassified'}\nURL: ${r.canonical_url}\nTitle: ${r.title}\nPublished: ${r.published_at||r.fetched_at||'unknown'}\nEvent: ${r.event_key||''}\nAction/object: ${r.action||''} / ${r.object||''}\nSummary: ${r.packet_summary||r.summary||''}\nChanged: ${r.what_changed||''}\nPoints: ${arr(r.key_points_json).join('; ')}\nPlaces: ${arr(r.places_json).join(', ')}\nOrganizations: ${arr(r.organizations_json).join(', ')}\nTopics: ${arr(r.topics_json).join(', ')}`).join('\n\n');
const feedback=(r:any)=>[...list(r?.unsupported,8).map((x:string)=>`Unsupported: ${x}`),...list(r?.framing,8).map((x:string)=>`Framing: ${x}`),text(r?.note,800)].filter(Boolean).join('\n').slice(0,2200);
async function lastFeedback(env:any,id:number){const r:any=await env.DB.prepare(`SELECT unsupported_claims_json,framing_problems_json,note FROM critic_reviews WHERE development_id=? ORDER BY id DESC LIMIT 1`).bind(id).first();return r?feedback({unsupported:arr(r.unsupported_claims_json),framing:arr(r.framing_problems_json),note:r.note}):''}
async function saveReview(env:any,id:number,r:any,attempt:number){await env.DB.prepare(`INSERT INTO critic_reviews(development_id,verdict,unsupported_claims_json,framing_problems_json,cluster_problem,relevance_problem,note,attempt,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,r.verdict,JSON.stringify(r.unsupported),JSON.stringify(r.framing),r.cluster_problem?1:0,r.relevance_problem?1:0,r.note||null,attempt,new Date().toISOString()).run()}
async function logStage(env:any,id:number,stage:string,outcome:string,purpose?:ChatPurpose,error?:any){try{await env.DB.prepare(`INSERT INTO engine_attempts(development_id,stage,outcome,model,error,created_at) VALUES(?,?,?,?,?,?)`).bind(id,stage,outcome,purpose?modelLabelFor(env,purpose):null,error?String(error?.message||error).slice(0,1600):null,new Date().toISOString()).run()}catch{}}

export async function markDevelopmentEditorialPending(env:any,id:number){
  const d:any=await env.DB.prepare(`SELECT status FROM developments WHERE id=?`).bind(id).first();if(!d||['filtered','merged'].includes(String(d.status)))return false;
  await env.DB.prepare(`UPDATE developments SET editorial_pending=1,editorial_dispatch_id=NULL,editorial_dispatched_at=NULL,updated_at=? WHERE id=?`).bind(new Date().toISOString(),id).run();return true;
}

export function fallbackDraft(job:any){const first=job.items[0]||{},title=text(job.dev.title_en||job.dev.title_id||first.title,500),summary=text(job.dev.summary_en||job.dev.summary_id||first.packet_summary||first.summary||title,1800),places=[...new Set(job.items.flatMap((item:any)=>arr(item.places_json)))],topics=[...new Set(job.items.flatMap((item:any)=>arr(item.topics_json)))];return {title_en:title,summary_en:summary,title_id:text(job.dev.title_id||title,500),summary_id:text(job.dev.summary_id||summary,1800),key_points_en:[],key_points_id:[],what_changed_en:'',what_changed_id:'',common_ground:[],source_notes:[],places,topics}}
export function draftFrom(o:any,fallback:any){return {title_en:text(o.title_en,500)||fallback.title_en,summary_en:text(o.summary_en,1800)||fallback.summary_en,title_id:text(o.title_id,500)||fallback.title_id,summary_id:text(o.summary_id,1800)||fallback.summary_id,key_points_en:list(o.key_points_en,5).map((x:string)=>text(x,500)),key_points_id:list(o.key_points_id,5).map((x:string)=>text(x,500)),what_changed_en:text(o.what_changed_en,1400),what_changed_id:text(o.what_changed_id,1400),common_ground:list(o.common_ground),source_notes:list(o.source_notes),places:list(o.places).length?list(o.places):fallback.places,topics:list(o.topics).length?list(o.topics):fallback.topics}}

async function writeDraftBatch(env:any,jobs:any[]){
  const prompt=jobs.map(j=>{const originals=j.items.filter((x:any)=>!x.syndicated_from_article_id),count=new Set(originals.map((x:any)=>x.publisher_id)).size;return `DEVELOPMENT ${j.id}\nOriginal publisher count: ${count}\nPrevious headline EN: ${j.dev.title_en||"None"}\nPrevious headline ID: ${j.dev.title_id||"None"}\nPrevious published summary: ${j.previous?.summary||"None; first publication"}\nPrevious key points: ${j.previous?.key_points_en_json||"[]"}\nPrevious publication time: ${j.previous?.created_at||"None"}\n${j.repair?`Previous critic feedback:\n${j.repair}\n`:''}${contextFor(j.items)}`}).join('\n\n================\n\n');
  const o:any=await runJson(env,[{role:'system',content:'You are West Papua Watch\'s restrained multilingual aggregation editor. Write one INDEPENDENT episode-level synthesis per DEVELOPMENT id. Use an informative concise headline that names the episode; keep individual promises and reactions in the summary or points. Aim for 8–14 words, with no catalogue of actions. Shorten an overlong previous headline first. Otherwise preserve the previous headline when it accurately names the episode; revise only when its scope is wrong or materially changes. Dates distinguish separate episodes involving the same person. Reports from different stops in one documented working visit can form one episode. Do not connect them merely because the actor and province match. what_changed must describe only material facts newly established relative to the previous published summary and key points. If no previous publication, or only repetition, return empty what_changed fields. Never use the section as another summary. English and careful Bahasa Indonesia only, not Papuan Malay. Every material claim must be supported by that Development\'s own source packets. Attribute sole-source or official/military/movement/NGO claims. A statement establishes its author made a claim, not independent proof of the claim. Evidence roles are not credibility scores. Preserve disagreement. Never mix evidence between Developments. Produce 3–5 concise key points in BOTH English and Bahasa Indonesia when the evidence supports them; do not pad weak evidence.'},{role:'user',content:prompt}],draftBatchSchema,'synthesis',Math.min(6000,1500+jobs.length*1120));
  const drafts=new Map<number,any>();for(const job of jobs){const raw=(o.items||[]).find((item:any)=>Number(item.development_id)===job.id);if(raw)drafts.set(job.id,draftFrom(raw,fallbackDraft(job)))}return drafts;
}

async function critiqueBatch(env:any,jobs:any[],drafts:Map<number,any>){
  const prompt=jobs.filter(j=>drafts.has(j.id)).map(j=>{const d=drafts.get(j.id);return `DEVELOPMENT ${j.id}\nDRAFT EN: ${d.title_en}\n${d.summary_en}\nKEY POINTS EN: ${d.key_points_en.join('; ')}\nDRAFT ID: ${d.title_id}\n${d.summary_id}\nKEY POINTS ID: ${d.key_points_id.join('; ')}\nWHAT CHANGED: ${d.what_changed_id}\n\nEVIDENCE\n${contextFor(j.items)}`}).join('\n\n================\n\n');
  const o:any=await runJson(env,[{role:'system',content:CRITIC_INSTRUCTION},{role:'user',content:prompt}],criticBatchSchema,'critic',Math.min(3200,760+jobs.length*520));
  return new Map<number,any>((o.items||[]).map((x:any)=>[Number(x.development_id),{verdict:x.verdict==='pass'?'pass':'revise',unsupported:list(x.unsupported_claims,8),framing:list(x.framing_problems,8),cluster_problem:x.cluster_problem===true,relevance_problem:x.relevance_problem===true,note:text(x.note,600)}] as [number,any]));
}

async function splitCluster(env:any,id:number,items:any[],_wasPublished:boolean){
  if(items.length<2)return[id];
  const total:any=await env.DB.prepare(`SELECT COUNT(*) n FROM development_articles WHERE development_id=?`).bind(id).first();
  if(Number(total?.n)!==items.length)throw new Error('Cluster exceeds bounded repair window; retain for review');
  const schema={type:'object',properties:{groups:{type:'array',items:{type:'array',items:{type:'integer'}}}},required:['groups'],additionalProperties:false};
  const response:any=await runJson(env,[{role:'system',content:'Partition these article IDs into distinct bounded episodes. Keep connected stops, promises and reactions during one identified working visit together. Same person, place or topic alone does not establish one episode. Use dates. Every supplied ID must appear exactly once; return at least two nonempty groups. Never invent IDs.'},{role:'user',content:items.map((r:any)=>`ARTICLE ${r.id} | ${r.published_at||r.fetched_at} | ${r.title} | ${r.event_key||''} | ${r.packet_summary||r.summary||''}`).join('\n')}],schema,'fast',1500);
  const groups=validatePartition(response.groups,items.map((r:any)=>Number(r.id)));
  if(!groups)throw new Error('Invalid episode partition; no memberships changed');
  // Retain the oldest article group at the existing public URL.
  const oldest=[...items].sort((a,b)=>Date.parse(a.published_at||a.fetched_at)-Date.parse(b.published_at||b.fetched_at))[0].id;
  groups.sort((a,b)=>Number(b.includes(oldest))-Number(a.includes(oldest)));
  await env.DB.prepare(`UPDATE developments SET status='held',editorial_pending=0 WHERE id=?`).bind(id).run();
  const ids=[id],now=new Date().toISOString();
  const statements:any[]=[];
  for(const group of groups.slice(1)){
    const item=items.find((r:any)=>r.id===group[0]);
    const ins:any=await env.DB.prepare(`INSERT INTO developments(title_en,summary_en,title_id,summary_id,event_signature,status,first_seen_at,updated_at,last_growth_at,pipeline_version,editorial_pending) VALUES(?,?,?,?,?,'held',?,?,?,?,0)`).bind(item.title,item.packet_summary||item.summary||'',item.title,item.packet_summary||item.summary||'',item.event_key||item.title,item.published_at||item.fetched_at,now,now,2).run();
    const newId=Number(ins.meta.last_row_id);ids.push(newId);
    for(const articleId of group){statements.push(env.DB.prepare(`UPDATE development_articles SET development_id=?,membership_method='episode-repair' WHERE development_id=? AND article_id=?`).bind(newId,id,articleId))}
  }
  // Membership changes commit together; failed preparation leaves the original intact.
  for(const target of ids){for(const table of ['development_issues','development_broad_issues','development_places','issue_delta_candidates'])statements.push(env.DB.prepare(`DELETE FROM ${table} WHERE development_id=?`).bind(target));statements.push(env.DB.prepare(`UPDATE developments SET status='candidate',issue_slug=NULL,retry_count=0,editorial_pending=1,editorial_dispatch_id=NULL,updated_at=? WHERE id=?`).bind(now,target))}
  await env.DB.batch(statements);
  for(const target of ids)await rebuildDevelopmentKnowledge(env,target);
  return ids;
}

async function writeIssueDelta(env:any,id:number,slug:string,d:any){try{const prior:any=await env.DB.prepare(`SELECT id FROM issue_delta_candidates WHERE development_id=? AND issue_slug=? ORDER BY id DESC LIMIT 1`).bind(id,slug).first(),now=new Date().toISOString();const en=text(d.what_changed_en||d.summary_en,1600),idText=text(d.what_changed_id||d.summary_id,1600);if(prior?.id)await env.DB.prepare(`UPDATE issue_delta_candidates SET delta_summary=?,delta_summary_id=?,significance='medium',status='published',created_at=? WHERE id=?`).bind(en,idText,now,prior.id).run();else await env.DB.prepare(`INSERT INTO issue_delta_candidates(issue_slug,development_id,delta_summary,delta_summary_id,significance,status,created_at) VALUES(?,?,?,?, 'medium','published',?)`).bind(slug,id,en,idText,now).run()}catch(e){console.warn('deterministic issue delta failed',id,slug,e)}}
function developmentSignature(draft:any){return `${draft.title_id}\n${draft.summary_id}\n${draft.what_changed_id}\nPlaces: ${draft.places.join(', ')}\nTopics: ${draft.topics.join(', ')}`.slice(0,2400)}
async function rank(env:any,id:number){const r:any=await env.DB.prepare(`SELECT COUNT(DISTINCT da.article_id) article_count,COUNT(DISTINCT CASE WHEN a.syndicated_from_article_id IS NULL THEN a.publisher_id END) source_count,MAX(CASE WHEN p.role IN ('local_newsroom','alternative_media') THEN 1 ELSE 0 END) local_source,MAX(COALESCE(a.published_at,a.fetched_at)) newest FROM development_articles da JOIN articles a ON a.id=da.article_id JOIN publishers p ON p.id=a.publisher_id WHERE da.development_id=?`).bind(id).first();const age=Math.max(0,(Date.now()-new Date(r?.newest||Date.now()).getTime())/36e5);return Number((Math.max(0,60-age*1.2)+Math.min(24,Number(r?.source_count||0)*8)+Math.min(12,Number(r?.article_count||0)*3)+(r?.local_source?10:0)).toFixed(2))}

async function finalize(env:any,id:number,dev:any,draft:any,sourceBrief=false){const now=new Date().toISOString(),signature=developmentSignature(draft);await env.DB.prepare(`INSERT INTO development_syntheses(development_id,title,summary,key_points_en_json,key_points_id_json,what_changed,what_changed_id,common_ground_json,source_notes_json,places_json,topics_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,draft.title_en,draft.summary_en,JSON.stringify(draft.key_points_en),JSON.stringify(draft.key_points_id),draft.what_changed_en,draft.what_changed_id,JSON.stringify(draft.common_ground),JSON.stringify(draft.source_notes),JSON.stringify(draft.places),JSON.stringify(draft.topics),now).run();let score=await rank(env,id);if(sourceBrief)score=Math.max(0,score-18);const unusable=/insufficient evidence|unable to synthesi[sz]e|cannot synthesi[sz]e|no overlapping facts|separate regional issues/i.test(draft.title_en+' '+draft.summary_en+' '+draft.common_ground.join(' '));const status=!unusable&&env.AUTO_PUBLISH==='true'?'published':'held';await env.DB.prepare(`UPDATE developments SET title_en=?,summary_en=?,title_id=?,summary_id=?,title_pmy=NULL,summary_pmy=NULL,event_signature=?,ranking_score=?,status=?,retry_count=0,editorial_pending=0,editorial_dispatch_id=NULL,editorial_dispatched_at=NULL,provider_backoff_count=0,editorial_not_before=NULL,updated_at=? WHERE id=?`).bind(draft.title_en,draft.summary_en,draft.title_id,draft.summary_id,signature,score,status,now,id).run();await upsertDevelopmentSearch(env,id,{title:draft.title_id,summary:draft.summary_id,event_signature:signature,places:draft.places,topics:draft.topics});const vector=await tryEmbedText(env,signature);if(vector){try{await env.ARTICLE_INDEX.upsert([{id:`dev:${id}`,values:vector,metadata:{kind:'development',developmentId:id,updatedAt:Date.now(),title:draft.title_id}}])}catch(e){console.warn('optional development Vectorize upsert failed',id,e)}}if(status==='published'){const rows:any=await env.DB.prepare(`SELECT issue_slug FROM development_issues WHERE development_id=?`).bind(id).all();const slugs:string[]=[...new Set<string>((rows.results||[]).map((r:any)=>String(r.issue_slug)).filter(Boolean))];if(!slugs.length&&dev?.issue_slug)slugs.push(String(dev.issue_slug));for(const slug of slugs)await writeIssueDelta(env,id,slug,draft)}return {status,ranking_score:score,sourceBrief}}

async function holdJobs(env:any,ids:number[],error:any){const quota=isGatewayQuotaError(error),malformed=isMalformedOutputError(error),now=new Date().toISOString();for(const id of ids){const row:any=await env.DB.prepare(`SELECT provider_backoff_count,status FROM developments WHERE id=?`).bind(id).first();const count=Number(row?.provider_backoff_count||0);const seconds=quota?Math.min(21600,900*Math.pow(2,Math.min(4,count))):malformed?300:3600;const notBefore=new Date(Date.now()+seconds*1000).toISOString();await env.DB.prepare(`UPDATE developments SET editorial_pending=1,editorial_dispatch_id=NULL,editorial_dispatched_at=NULL,editorial_not_before=?,provider_backoff_count=COALESCE(provider_backoff_count,0)+?,status=CASE WHEN status='published' THEN 'published' ELSE 'held' END,updated_at=? WHERE id=?`).bind(notBefore,quota?1:0,now,id).run();await logStage(env,id,'editorial-batch','held',undefined,error)}return {status:'held',ids,reason:quota?'quota':malformed?'malformed':'provider',message:String(error?.message||error).slice(0,500)}}

export async function processEditorialJob(env:any,message:any){
  const dispatchId=String(message?.dispatchId||'');const requested=(Array.isArray(message?.developmentIds)?message.developmentIds:[message?.developmentId]).map(Number).filter(Number.isFinite);
  if(!dispatchId||!requested.length)return {status:'stale-dispatch'};
  const jobs:any[]=[];
  for(const id of requested){const dev:any=await env.DB.prepare(`SELECT status,title_en,title_id,summary_en,summary_id,issue_slug,retry_count,editorial_not_before,editorial_dispatch_id FROM developments WHERE id=?`).bind(id).first();if(!dev||['filtered','merged'].includes(String(dev.status))||dev.editorial_dispatch_id!==dispatchId)continue;const items=await loadItems(env,id);if(!items.length)continue;const previous=dev.status==='published'?await env.DB.prepare(`SELECT summary,key_points_en_json,created_at FROM development_syntheses WHERE development_id=? ORDER BY id DESC LIMIT 1`).bind(id).first():null;jobs.push({id,dev,items,previous,attempt:Number(dev.retry_count||0)+1,repair:await lastFeedback(env,id)})}
  if(!jobs.length)return {status:'stale-dispatch'};
  for(const j of jobs)await logStage(env,j.id,'writer','started','synthesis');
  let drafts:Map<number,any>;try{drafts=await writeDraftBatch(env,jobs)}catch(e){for(const j of jobs)await logStage(env,j.id,'writer','error','synthesis',e);return holdJobs(env,jobs.map(j=>j.id),e)}
  for(const j of jobs)await logStage(env,j.id,'writer',drafts.has(j.id)?'success':'error','synthesis',drafts.has(j.id)?undefined:new Error('writer batch omitted development'));
  const missingWriter=jobs.filter(j=>!drafts.has(j.id));if(missingWriter.length)await holdJobs(env,missingWriter.map(j=>j.id),new Error('malformed writer batch omitted development'));
  const criticJobs=jobs.filter(j=>drafts.has(j.id));if(!criticJobs.length)return {status:'held'};
  for(const j of criticJobs)await logStage(env,j.id,'critic','started','critic');
  let reviews:Map<number,any>;try{reviews=await critiqueBatch(env,criticJobs,drafts)}catch(e){for(const j of criticJobs)await logStage(env,j.id,'critic','error','critic',e);return holdJobs(env,criticJobs.map(j=>j.id),e)}
  const results:any[]=[];
  for(const j of criticJobs){const lease:any=await env.DB.prepare(`SELECT editorial_dispatch_id FROM developments WHERE id=?`).bind(j.id).first();if(lease?.editorial_dispatch_id!==dispatchId){results.push({id:j.id,status:'stale-dispatch'});continue}const draft=drafts.get(j.id),review=reviews.get(j.id);if(!review){await holdJobs(env,[j.id],new Error('malformed critic batch omitted development'));continue}await logStage(env,j.id,'critic','success','critic');await saveReview(env,j.id,review,j.attempt);const clusterProblem=review.cluster_problem&&j.items.length>1,relevanceProblem=review.relevance_problem;
    if(clusterProblem){try{const ids=await splitCluster(env,j.id,j.items,j.dev.status==='published');results.push({id:j.id,status:'reclustered',ids})}catch(e){await env.DB.prepare(`UPDATE developments SET status='held' WHERE id=?`).bind(j.id).run();await holdJobs(env,[j.id],e)}continue}
    if(relevanceProblem){await env.DB.prepare(`UPDATE developments SET status='held',editorial_pending=0,editorial_dispatch_id=NULL,updated_at=? WHERE id=?`).bind(new Date().toISOString(),j.id).run();results.push({id:j.id,status:'held-relevance'});continue}
    if(review.verdict==='pass'){results.push({id:j.id,...await finalize(env,j.id,j.dev,draft,false)});continue}
    if(j.attempt>=MAX_LOGICAL_REVISIONS){await env.DB.prepare(`UPDATE developments SET status='held',editorial_pending=0,editorial_dispatch_id=NULL WHERE id=?`).bind(j.id).run();results.push({id:j.id,status:'held-editorial-review'});continue}
    await env.DB.prepare(`UPDATE developments SET retry_count=retry_count+1,editorial_pending=1,editorial_dispatch_id=NULL,editorial_dispatched_at=NULL,status=CASE WHEN status='published' THEN 'published' ELSE 'retrying' END,updated_at=? WHERE id=?`).bind(new Date().toISOString(),j.id).run();results.push({id:j.id,status:'pending-revision',attempt:j.attempt});
  }
  return {status:'processed',dispatchId,results};
}

export async function queueDevelopmentForEditorial(env:any,id:number,_force=false){return markDevelopmentEditorialPending(env,id)}

export async function enqueueEditorialBacklog(env:any,limit=MAX_EDITORIAL_BATCH){
  const rows:any=await env.DB.prepare(`SELECT id FROM developments WHERE pipeline_version>=2 AND editorial_pending=1 AND status NOT IN ('filtered','merged') AND (editorial_not_before IS NULL OR editorial_not_before<=strftime('%Y-%m-%dT%H:%M:%fZ','now')) ORDER BY CASE WHEN status='published' THEN 0 ELSE 1 END,updated_at ASC LIMIT ?`).bind(Math.min(MAX_EDITORIAL_BATCH,Math.max(1,limit))).all();
  const ids=(rows.results||[]).map((r:any)=>Number(r.id)).filter(Number.isFinite);if(!ids.length)return {checked:0,queued:0};const dispatchId=crypto.randomUUID(),now=new Date().toISOString();
  for(const id of ids)await env.DB.prepare(`UPDATE developments SET editorial_pending=0,editorial_dispatch_id=?,editorial_dispatched_at=?,status=CASE WHEN status='published' THEN 'published' ELSE 'editorial_queued' END,updated_at=? WHERE id=?`).bind(dispatchId,now,now,id).run();
  try{await env.EDITORIAL_QUEUE.send({kind:'editorial',dispatchId,developmentIds:ids})}catch(e){for(const id of ids)await env.DB.prepare(`UPDATE developments SET editorial_pending=1,editorial_dispatch_id=NULL,editorial_dispatched_at=NULL,status=CASE WHEN status='editorial_queued' THEN 'held' ELSE status END,updated_at=? WHERE id=?`).bind(new Date().toISOString(),id).run();throw e}return {checked:ids.length,queued:ids.length,dispatchId};
}
