import { runChat } from '../llm';

const arr=(value:any)=>{try{return JSON.parse(String(value||'[]')) as string[]}catch{return[]}};
const jsonObject=(raw:string)=>{try{return JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0]||'{}')}catch{return{}}};
const text=(value:any,max:number)=>String(value||'').trim().slice(0,max);
const list=(value:any,max=12)=>Array.isArray(value)?value.map(String).map(x=>x.trim()).filter(Boolean).slice(0,max):[];

async function loadItems(env:any,developmentId:number){
  const rows:any=await env.DB.prepare(`SELECT a.id,a.title,a.summary,a.published_at,a.fetched_at,a.syndicated_from_article_id,a.canonical_url,p.id publisher_id,p.name publisher,p.role,sp.summary packet_summary,sp.key_points_json,sp.what_changed,sp.places_json,sp.organizations_json,sp.topics_json,sp.issue_candidates_json FROM development_articles da JOIN articles a ON a.id=da.article_id JOIN publishers p ON p.id=a.publisher_id LEFT JOIN story_packets sp ON sp.article_id=a.id WHERE da.development_id=? ORDER BY COALESCE(a.published_at,a.fetched_at) DESC LIMIT 10`).bind(developmentId).all();return rows.results||[];
}
function contextFor(items:any[]){return items.map((r:any,i:number)=>`[S${i+1}] ${r.publisher} (${r.role})\nURL: ${r.canonical_url}\nTitle: ${r.title}\n${r.packet_summary||r.summary||''}\nWhat changed: ${r.what_changed||''}\nKey points: ${arr(r.key_points_json).join('; ')}\nPlaces: ${arr(r.places_json).join(', ')}\nOrganizations: ${arr(r.organizations_json).join(', ')}\nTopics: ${arr(r.topics_json).join(', ')}`).join('\n\n')}
async function writeDraft(env:any,items:any[],critique=''){
  const original=items.filter((r:any)=>!r.syndicated_from_article_id);const sourceCount=new Set(original.map((r:any)=>r.publisher_id)).size;const context=contextFor(items);
  const prompt=`Write one calm, precise event-level development from the supplied reporting. This is an aggregator, not an original eyewitness. Every factual claim must be supportable from the records below. If only one original publisher reports a material claim, attribute it explicitly in the summary (for example, "Jubi reports..."). Preserve uncertainty and disagreement. Do not turn a government, military, movement, NGO, or other attributed claim into anonymous fact. Do not use advocacy slogans unless the source is being attributed. Return JSON only with title, summary, title_pmy, summary_pmy, what_changed, common_ground, source_notes, places, topics. title_pmy and summary_pmy are concise Papuan Malay drafts; preserve proper names and meaning rather than embellishing. Original publisher count: ${sourceCount}.${critique?`\n\nPrevious critic feedback to fix:\n${critique}`:''}\n\n${context}`;
  const raw=await runChat(env,[{role:'system',content:'Write publication-ready aggregation copy. Be restrained, readable, source-aware, and concrete.'},{role:'user',content:prompt}],'synthesis',920);const obj=jsonObject(raw);return {title:text(obj.title,500),summary:text(obj.summary,1800),title_pmy:text(obj.title_pmy,500),summary_pmy:text(obj.summary_pmy,1800),what_changed:text(obj.what_changed,1400),common_ground:list(obj.common_ground),source_notes:list(obj.source_notes),places:list(obj.places),topics:list(obj.topics)};
}
async function critiqueDraft(env:any,items:any[],draft:any){
  const prompt=`Audit this aggregation draft strictly against the supplied source packets. Return JSON only with verdict (pass|revise|hold), confidence (0-1), unsupported_claims (array), framing_problems (array), cluster_problem (boolean), relevance_problem (boolean), note (short string). Check: every factual assertion has support; attributed claims remain attributed; the headline does not overclaim; syndication is not treated as independent corroboration; all records actually concern one concrete development; the development is materially relevant to West Papua / the western half of New Guinea; the Papuan Malay draft preserves the English meaning and introduces no new claims. A single credible local report may pass if its claims are clearly attributed.\n\nDRAFT\nTitle: ${draft.title}\nSummary: ${draft.summary}\nPMY title: ${draft.title_pmy}\nPMY summary: ${draft.summary_pmy}\n\nSOURCES\n${contextFor(items)}`;
  const raw=await runChat(env,[{role:'system',content:'You are an evidence critic, not a second columnist. Fail unsupported certainty and bad clustering; do not fail a story merely because it has one source when attribution is explicit.'},{role:'user',content:prompt}],'fast',420);const obj=jsonObject(raw);return {verdict:['pass','revise','hold'].includes(obj.verdict)?obj.verdict:'hold',confidence:Math.max(0,Math.min(1,Number(obj.confidence)||0)),unsupported:list(obj.unsupported_claims,8),framing:list(obj.framing_problems,8),cluster_problem:obj.cluster_problem===true,relevance_problem:obj.relevance_problem===true,note:text(obj.note,500)};
}
function critiqueText(review:any){return [...review.unsupported.map((x:string)=>`Unsupported: ${x}`),...review.framing.map((x:string)=>`Framing: ${x}`),review.note].filter(Boolean).join('\n').slice(0,2200)}
async function writeIssueDelta(env:any,developmentId:number,issueSlug:string,draft:any,status:string){
  const existing:any=await env.DB.prepare(`SELECT id FROM issue_delta_candidates WHERE development_id=? ORDER BY id DESC LIMIT 1`).bind(developmentId).first();
  const prompt=`Issue: ${issueSlug}\nNew development: ${draft.title}\n${draft.summary}\nWhat changed: ${draft.what_changed}\nReturn JSON only with delta_summary and significance (low|medium|high). Describe only the new change, not the entire issue.`;
  try{const raw=await runChat(env,[{role:'system',content:'Write a concise issue-timeline delta supported by the development.'},{role:'user',content:prompt}],'fast',240);const obj=jsonObject(raw);if(!obj.delta_summary)return;const now=new Date().toISOString(),significance=['low','medium','high'].includes(obj.significance)?obj.significance:'medium',delta=text(obj.delta_summary,1600);if(existing?.id)await env.DB.prepare(`UPDATE issue_delta_candidates SET delta_summary=?,significance=?,status=?,created_at=? WHERE id=?`).bind(delta,significance,status,now,existing.id).run();else await env.DB.prepare(`INSERT INTO issue_delta_candidates(issue_slug,development_id,delta_summary,significance,status,created_at) VALUES(?,?,?,?,?,?)`).bind(issueSlug,developmentId,delta,significance,status,now).run()}catch{}
}

export async function publishDevelopment(env:any,developmentId:number){
  const items=await loadItems(env,developmentId);if(!items.length)return {status:'empty'};const dev:any=await env.DB.prepare(`SELECT status,issue_slug FROM developments WHERE id=?`).bind(developmentId).first();
  let draft=await writeDraft(env,items);if(!draft.title||!draft.summary)return {status:'held',reason:'empty-draft'};let review=await critiqueDraft(env,items,draft);
  if(review.verdict==='revise'&&!review.cluster_problem&&!review.relevance_problem){draft=await writeDraft(env,items,critiqueText(review));if(draft.title&&draft.summary)review=await critiqueDraft(env,items,draft)}
  const pass=review.verdict==='pass'&&review.confidence>=.72&&!review.cluster_problem&&!review.relevance_problem;const now=new Date().toISOString();
  if(!pass){if(dev?.status!=='published')await env.DB.prepare(`UPDATE developments SET status='held',updated_at=? WHERE id=?`).bind(now,developmentId).run();return {status:dev?.status==='published'?'published':'held',review}}
  await env.DB.prepare(`INSERT INTO development_syntheses(development_id,title,summary,what_changed,common_ground_json,source_notes_json,places_json,topics_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(developmentId,draft.title,draft.summary,draft.what_changed,JSON.stringify(draft.common_ground),JSON.stringify(draft.source_notes),JSON.stringify(draft.places),JSON.stringify(draft.topics),now).run();
  const publish=env.AUTO_PUBLISH==='true';const status=publish?'published':'candidate';await env.DB.prepare(`UPDATE developments SET title_en=?,title_pmy=?,summary_en=?,summary_pmy=?,status=?,updated_at=? WHERE id=?`).bind(draft.title,draft.title_pmy||draft.title,draft.summary,draft.summary_pmy||draft.summary,status,now,developmentId).run();if(dev?.issue_slug)await writeIssueDelta(env,developmentId,dev.issue_slug,draft,publish?'published':'candidate');return {status,review};
}

export async function revisitCandidateDevelopments(env:any,limit=10){const rows:any=await env.DB.prepare(`SELECT id FROM developments WHERE status='candidate' ORDER BY updated_at ASC LIMIT ?`).bind(limit).all();let published=0,held=0;for(const row of rows.results||[]){const result:any=await publishDevelopment(env,Number(row.id));if(result.status==='published')published++;if(result.status==='held')held++}return {checked:(rows.results||[]).length,published,held}}
