import { runChat } from '../llm';
import { publishDevelopment } from './editorial';

const issueRules:[string,RegExp][]=[
  ['mining-raja-ampat',/raja ampat|gag nikel|waigeo/i],['lake-sentani-watershed',/sentani|cycloop|cagar alam cycloop/i],['south-papua-food-energy-estate',/merauke|papua selatan|food estate|cetak sawah|jagebob/i],['conflict-displacement-access',/pengungsi|displacement|conflict|konflik|military|militer|intan jaya|puncak|nduga/i],['women-gender',/perempuan|mama-mama|women|gender/i],['culture-memory-expression',/seni|art|film|musik|music|sastra|literature|udeido|mambesak/i],['political-status-representation',/otonomi|autonomy|self-determination|merdeka|political status|status politik/i]
];
export const matchIssue=(text:string)=>issueRules.find(([,rx])=>rx.test(text))?.[0]||null;
const arr=(value:any)=>{try{return JSON.parse(String(value||'[]')) as string[]}catch{return[]}};
const overlap=(a:string[],b:string[])=>{const aa=new Set(a.map(x=>x.toLowerCase()));const bb=new Set(b.map(x=>x.toLowerCase()));if(!aa.size||!bb.size)return 0;let n=0;for(const x of aa)if(bb.has(x))n++;return n/Math.max(aa.size,bb.size)};
const dateScore=(a?:string,b?:string)=>{if(!a||!b)return .35;const d=Math.abs(new Date(a).getTime()-new Date(b).getTime())/864e5;if(!Number.isFinite(d))return .35;if(d<=1)return 1;if(d<=3)return .8;if(d<=7)return .55;if(d<=21)return .25;return 0};
async function packet(env:any,id:number){return await env.DB.prepare(`SELECT * FROM story_packets WHERE article_id=?`).bind(id).first()}

async function sameEvent(env:any,a:any,b:any,score:number):Promise<boolean>{
  const prompt=`Determine whether these two records describe the same concrete real-world development, not merely the same topic. Return JSON only: {"same_event":true|false,"confidence":0-1}.\nHeuristic score: ${score.toFixed(3)}\nA: ${a.title}\n${a.packet?.summary||a.summary||''}\nDate: ${a.packet?.event_date||a.published_at||''}\nPlaces: ${arr(a.packet?.places_json).join(', ')}\nOrganizations: ${arr(a.packet?.organizations_json).join(', ')}\n\nB: ${b.title}\n${b.packet?.summary||b.summary||''}\nDate: ${b.packet?.event_date||b.published_at||''}\nPlaces: ${arr(b.packet?.places_json).join(', ')}\nOrganizations: ${arr(b.packet?.organizations_json).join(', ')}`;
  try{const raw=await runChat(env,[{role:'system',content:'Be conservative about merging events. Same place, person, organization or broad topic alone is not enough.'},{role:'user',content:prompt}],'fast',140);const json=JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0]||'{}');return json.same_event===true&&Number(json.confidence||0)>=.7}catch{return false}
}

export async function clusterArticle(env:any,article:any,vector:number[]){
  const existing=await env.DB.prepare(`SELECT development_id FROM development_articles WHERE article_id=? LIMIT 1`).bind(article.id).first();if(existing?.development_id){const id=Number(existing.development_id);await publishDevelopment(env,id);return id}const currentPacket=await packet(env,article.id);const current={...article,packet:currentPacket};
  const result:any=await env.ARTICLE_INDEX.query(vector,{topK:10,returnMetadata:'all'});const candidates=(result?.matches||[]).filter((m:any)=>String(m.id)!==String(article.id)&&Number(m.score||0)>=.58);let developmentId:number|null=null;
  for(const match of candidates.slice(0,5)){
    const candidate:any=await env.DB.prepare(`SELECT a.*, da.development_id FROM articles a LEFT JOIN development_articles da ON da.article_id=a.id WHERE a.id=?`).bind(Number(match.id)).first();if(!candidate)continue;candidate.packet=await packet(env,candidate.id);
    const semantic=Number(match.score||0);const place=overlap(arr(currentPacket?.places_json),arr(candidate.packet?.places_json));const org=overlap(arr(currentPacket?.organizations_json),arr(candidate.packet?.organizations_json));const topic=overlap(arr(currentPacket?.topics_json),arr(candidate.packet?.topics_json));const dates=dateScore(currentPacket?.event_date||article.published_at,candidate.packet?.event_date||candidate.published_at);const score=.62*semantic+.14*dates+.11*place+.08*org+.05*topic;if(score<.61)continue;const deterministic=score>=.88&&semantic>=.78&&(place>.2||org>.2);if(!deterministic&&!await sameEvent(env,current,candidate,score))continue;
    developmentId=candidate.development_id?Number(candidate.development_id):null;if(!developmentId){const issue=matchIssue(`${candidate.title} ${candidate.packet?.summary||candidate.summary||''} ${arr(candidate.packet?.issue_candidates_json).join(' ')}`);const inserted:any=await env.DB.prepare(`INSERT INTO developments(issue_slug,title_en,summary_en,status,first_seen_at,updated_at) VALUES(?,?,?,?,?,?)`).bind(issue,candidate.title,candidate.packet?.summary||candidate.summary||'','candidate',candidate.published_at||candidate.fetched_at,new Date().toISOString()).run();developmentId=Number(inserted.meta.last_row_id);await env.DB.prepare(`INSERT OR IGNORE INTO development_articles(development_id,article_id,membership_score,membership_method) VALUES(?,?,?,?)`).bind(developmentId,candidate.id,score,deterministic?'multisignal':'multisignal+llm').run()}break;
  }
  if(!developmentId){const issue=matchIssue(`${article.title} ${currentPacket?.summary||article.summary||''} ${arr(currentPacket?.issue_candidates_json).join(' ')}`);const inserted:any=await env.DB.prepare(`INSERT INTO developments(issue_slug,title_en,summary_en,status,first_seen_at,updated_at) VALUES(?,?,?,?,?,?)`).bind(issue,article.title,currentPacket?.summary||article.summary||'','candidate',article.published_at||article.fetched_at,new Date().toISOString()).run();developmentId=Number(inserted.meta.last_row_id)}
  await env.DB.prepare(`INSERT OR IGNORE INTO development_articles(development_id,article_id,membership_score,membership_method) VALUES(?,?,?,?)`).bind(developmentId,article.id,1,'primary').run();await publishDevelopment(env,developmentId);return developmentId;
}
