export type CorpusItem={id:string;title:string;text:string;url:string;publisher:string;tags:string[]};
export const CORPUS:CorpusItem[]=[
{id:'issue-raja',title:'Mining in Raja Ampat',text:'Mining permits, operating sites, marine and terrestrial ecosystems, customary land and public scrutiny across Raja Ampat. Recent reporting focuses on mining pressure, permit pathways and ecological concerns.',url:'https://westpapua.watch/issues/mining-raja-ampat/',publisher:'West Papua Watch',tags:['raja ampat','mining','environment','extractivism']},
{id:'source-greenpeace-raja',title:'Greenpeace Clarifies Findings on the Raja Ampat’s Nickel Report',text:'Greenpeace Southeast Asia publication on its findings concerning nickel mining in Raja Ampat.',url:'https://www.greenpeace.org/southeastasia/press/69207/greenpeace-clarifies-findings-on-the-raja-ampats-nickel-report/',publisher:'Greenpeace Southeast Asia',tags:['raja ampat','nickel','mining']},
{id:'source-mongabay-raja',title:'Ekspansi Tambang Nikel Terus Hantui Raja Ampat',text:'Mongabay Indonesia reporting on nickel mining pressure and environmental concern in Raja Ampat.',url:'https://mongabay.co.id/2026/08/08/ekspansi-tambang-nikel-terus-hantui-raja-ampat/',publisher:'Mongabay Indonesia',tags:['raja ampat','nickel','environment']},
{id:'issue-sentani',title:'Lake Sentani watershed',text:'Water quality, sedimentation, mining pressure, biodiversity and livelihoods around Lake Sentani and the Cycloop foothills. Jubi and Mongabay reported in August 2026 on upstream illegal gold mining and sediment entering Lake Sentani.',url:'https://westpapua.watch/issues/lake-sentani-watershed/',publisher:'West Papua Watch',tags:['lake sentani','cycloop','illegal mining','environment']},
{id:'source-mongabay-sentani',title:'Ancaman Tambang Emas Ilegal di Hulu Danau Sentani',text:'Mongabay Indonesia report on illegal gold mining upstream, sedimentation, water quality and impacts around Lake Sentani.',url:'https://mongabay.co.id/2026/08/27/ancaman-tambang-emas-ilegal-di-hulu-danau-sentani/',publisher:'Mongabay Indonesia',tags:['lake sentani','mining','water','environment']},
{id:'issue-merauke',title:'South Papua food and energy estate',text:'Land, forests, livelihoods and large-scale food and energy projects being developed in and around Merauke.',url:'https://westpapua.watch/issues/south-papua-food-energy-estate/',publisher:'West Papua Watch',tags:['merauke','land','food estate','psn','gastrocolonialism']},
{id:'source-jubi-hria',title:'Human Rights Impact Reports on Papua Selatan Strategic Projects Launched',text:'Jubi report on two Human Rights Impact Assessment reports concerning national strategic projects in South Papua, land dispossession, environmental impacts and vulnerable groups including women and children.',url:'https://en.jubi.id/human-rights-impact-reports-on-papua-selatan-strategic-projects-launched/',publisher:'Jubi / West Papua Daily',tags:['merauke','south papua','women','land','psn']},
{id:'source-pusaka',title:'PUSAKA news and publications',text:'Yayasan Pusaka Bentala Rakyat publishes reporting and advocacy material on Indigenous rights, forests, land, national strategic projects and environmental change in Tanah Papua.',url:'https://pusaka.or.id/en/news/',publisher:'Yayasan Pusaka Bentala Rakyat',tags:['pusaka','indigenous rights','land','forest','merauke']},
{id:'issue-conflict',title:'Conflict, displacement and access',text:'Civilian displacement, access to services and independent monitoring in conflict-affected areas of West Papua.',url:'https://westpapua.watch/issues/conflict-displacement-access/',publisher:'West Papua Watch',tags:['human rights','displacement','conflict','access']},
{id:'source-hrm-q2',title:'The Papua Monitor: Q2/2026',text:'Human Rights Monitor quarterly report covering human rights, conflict, displacement, political developments and international responses in West Papua from April through June 2026.',url:'https://humanrightsmonitor.org/wp-content/uploads/2026/07/HRM-PMR-2026-03-Q2-2026-Papua-Monitor.pdf',publisher:'Human Rights Monitor',tags:['human rights','displacement','conflict','monitoring']},
{id:'history-1962',title:'1962 — The New York Agreement',text:'Indonesia and the Netherlands signed the Agreement concerning West New Guinea on 15 August 1962. It provided for transfer of administration through the United Nations Temporary Executive Authority before administration passed to Indonesia in 1963.',url:'https://westpapua.watch/history/',publisher:'West Papua Watch',tags:['1962','new york agreement','untea','history']},
{id:'source-un-1962',title:'Agreement concerning West New Guinea (West Irian)',text:'United Nations Treaty Series record of the agreement between Indonesia and the Netherlands signed in New York on 15 August 1962.',url:'https://treaties.un.org/Pages/showDetails.aspx?clang=_en&objid=0800000280133981',publisher:'United Nations Treaty Collection',tags:['1962','new york agreement','un']},
{id:'history-1969',title:'1969 — The Act of Free Choice',text:'The 1969 consultation remains central to disputes over West Papua’s political history. The record is best read through clearly attributed institutional documents, scholarship and Papuan accounts.',url:'https://westpapua.watch/history/',publisher:'West Papua Watch',tags:['1969','act of free choice','history','political status']},
{id:'source-un-2504',title:'General Assembly Resolution 2504 (XXIV)',text:'United Nations General Assembly resolution adopted on 19 November 1969 concerning the Agreement between Indonesia and the Netherlands regarding West New Guinea (West Irian).',url:'https://digitallibrary.un.org/record/202193',publisher:'United Nations Digital Library',tags:['1969','un','resolution 2504']},
{id:'source-musgrave',title:'An analysis of the 1969 Act of Free Choice in West Papua',text:'Thomas D. Musgrave scholarly chapter published by Cambridge University Press examining the 1969 Act of Free Choice and questions of self-determination.',url:'https://www.cambridge.org/core/books/sovereignty-statehood-and-state-responsibility/an-analysis-of-the-1969-act-of-free-choice-in-west-papua/6DB756FCBC96D81B76B663846A8BDE53',publisher:'Cambridge University Press',tags:['1969','act of free choice','research']},
{id:'issue-women',title:'Women & Gender',text:'Indigenous women’s leadership, rights, land relationships, care, cultural transmission and gender-based violence.',url:'https://westpapua.watch/issues/women-gender/',publisher:'West Papua Watch',tags:['women','gender','indigenous women','rights']},
{id:'event-rmw',title:'Read My World 2026 — Oceanic Solidarity',text:'Read My World runs from 10 to 12 September 2026 at Tolhuistuin in Amsterdam. The 2026 programme includes special guests from West Papua and Maluku and programmes across literature, music, art and public discussion.',url:'https://readmyworld.nl/',publisher:'Read My World',tags:['event','amsterdam','read my world','oceanic solidarity']},
{id:'culture-udeido',title:'Udeido Collective',text:'Udeido Collective was established in 2018 as a space for Papuan artists to explore social and humanities phenomena in Papua through visual art and collective practice.',url:'https://www.biennalejogja.org/2021/en/seniman/udeido-collective/',publisher:'Biennale Jogja',tags:['udeido','art','collective','papua']}
];
