import type { SourceConfig } from '../types';
import {itemType,normalizeLibraryItem} from '../../../../shared/library';
import {issueSlugsFor} from '../knowledge';
export const libraryCandidate=(packet:any,policy='selective')=>policy!=='none'&&packet?.library_worthy===true&&Boolean(packet.library_reason?.trim());
export async function maybeResourceCandidate(env:any,article:any,source:SourceConfig){
 const packet=article.packet||{};if(!libraryCandidate(packet,source.libraryPolicy))return;
 const kind=itemType(packet.item_type),topics=issueSlugsFor(`${article.title} ${packet.summary||''}`,packet.issue_candidates||[]),places=[...new Set<string>(packet.places||[])].slice(0,12),tags=[...new Set<string>(packet.topics||[])].slice(0,24),now=new Date().toISOString();
 const item=normalizeLibraryItem({url:article.canonicalUrl,itemType:kind,published_at:article.publishedAt,language:article.language});
 await env.DB.prepare(`INSERT INTO resource_candidates(article_id,title,source_url,publisher_id,kind,status,created_at,description,tags_json,languages_json,updated_at,item_type,format,published_at,evidence_roles_json,topics_json,places_json,inclusion_reason) VALUES(?,?,?,?,?,'candidate',?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source_url) DO UPDATE SET title=excluded.title,publisher_id=excluded.publisher_id,kind=excluded.kind,description=excluded.description,tags_json=excluded.tags_json,languages_json=excluded.languages_json,updated_at=excluded.updated_at,item_type=excluded.item_type,format=excluded.format,published_at=COALESCE(excluded.published_at,resource_candidates.published_at),evidence_roles_json=excluded.evidence_roles_json,topics_json=excluded.topics_json,places_json=excluded.places_json,inclusion_reason=excluded.inclusion_reason`).bind(article.id,article.title,article.canonicalUrl,source.id,kind,now,packet.summary||article.description||'',JSON.stringify(tags),JSON.stringify(item.languages),now,kind,item.format,item.publishedAt||null,JSON.stringify(packet.evidence_roles||[]),JSON.stringify(topics),JSON.stringify(places),packet.library_reason).run();
 const row:any=await env.DB.prepare(`SELECT id FROM resource_candidates WHERE source_url=?`).bind(article.canonicalUrl).first();if(!row)return;
 const relations=topics.map(id=>['topic',id]).concat(places.map(id=>['place',id]));const stories:any=await env.DB.prepare(`SELECT development_id FROM development_articles WHERE article_id=?`).bind(article.id).all();for(const r of stories.results||[])relations.push(['story',String(r.development_id)]);
 await env.DB.batch([env.DB.prepare(`DELETE FROM resource_relations WHERE resource_id=? AND origin='classifier'`).bind(row.id),...relations.map(([kind,id])=>env.DB.prepare(`INSERT OR IGNORE INTO resource_relations(resource_id,target_kind,target_id) VALUES(?,?,?)`).bind(row.id,kind,id))]);
}
