import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {normalize,safeUrl,fetchPublic} from '../../src/lib/etnos/data.mjs';
assert.equal(safeUrl('javascript:alert(1)'), '');
assert.throws(()=>normalize({},'news'));
assert.deepEqual(normalize({posts:[{post:{title:'Hidden',nsfw:true}}]},'forum'),[]);
const news=normalize({items:[{id:42,title:{id:'Judul'},summary:{id:'Ringkasan'},places:[{latitude:null,longitude:null}]}]},'news');
assert.equal(news[0].url,'https://westpapua.watch/id/story/?id=42');
assert.equal(news[0].coordinates,undefined);
assert.equal(news[0].title,'Judul');
const forum=normalize({posts:[{post:{title:'Post',ap_id:'https://example.org/post/1'},community:{title:'Community'},creator:{user_name:'user'}}]},'forum');
assert.equal(forum.length,1);
await assert.rejects(fetchPublic('https://example.org',async()=>new Response('',{status:502})));
const wiki=JSON.parse(readFileSync(new URL('../../src/lib/etnos/wiki.json',import.meta.url),'utf8'));
assert(wiki.items.length>0);assert(wiki.items.every(i=>i.coordinates.every(Number.isFinite)&&i.url.startsWith('https://id.wikipedia.org/wiki/')));
const ui=readFileSync(new URL('../../src/lib/etnos/interface.ts',import.meta.url),'utf8');
assert.equal((ui.match(/new maplibregl.Map\(/g)||[]).length,1);
assert(!ui.includes('innerHTML'));
const config=JSON.parse(readFileSync(new URL('../../wrangler.etnos-preview.jsonc',import.meta.url),'utf8'));
for(const key of ['services','r2_buckets','d1_databases'])assert(!(key in config));
console.log('ETNOS: adapters, unsafe URLs, errors, reference coordinates, single map instance and preview isolation PASS');
