import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {build} from 'esbuild';
const moduleAt=async path=>{const r=await build({entryPoints:[path],bundle:true,write:false,format:'esm',platform:'node'});return import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'))};
const {enqueueEditorialBacklog,processEditorialJob}=await moduleAt('services/watch-engine/src/cluster/editorial.ts');
const sqlite=new DatabaseSync(':memory:');sqlite.exec(`CREATE TABLE developments(id INTEGER PRIMARY KEY,pipeline_version INTEGER DEFAULT 2,editorial_pending INTEGER DEFAULT 1,status TEXT DEFAULT 'held',editorial_dispatch_id TEXT,editorial_dispatched_at TEXT,editorial_started_at TEXT,editorial_not_before TEXT,updated_at TEXT);`);
const DB={prepare(sql){const stmt=sqlite.prepare(sql);let args=[];const api={bind(...a){args=a;return api},async run(){return {meta:{changes:Number(stmt.run(...args).changes)}}},async all(){return {results:stmt.all(...args)}},async first(){return stmt.get(...args)}};return api}};
const sent=[];const env={DB,EDITORIAL_QUEUE:{async send(message){sent.push(message)}}};
sqlite.exec(`INSERT INTO developments(id,status,updated_at) VALUES(1,'held','2026-01-01'),(2,'published','2026-02-01'); INSERT INTO developments(id,editorial_pending,editorial_dispatch_id,editorial_dispatched_at,updated_at) VALUES(3,0,'expired',datetime('now','-1 hour'),'2026-03-01'),(4,0,'fresh',datetime('now'),'2026-04-01');`);
let result=await enqueueEditorialBacklog(env,2);assert.equal(result.recovered,1);assert.deepEqual(sent.map(m=>m.developmentIds),[[1],[2]]);assert.equal(sqlite.prepare('SELECT editorial_pending p FROM developments WHERE id=3').get().p,1);assert.equal(sqlite.prepare('SELECT editorial_dispatch_id d FROM developments WHERE id=4').get().d,'fresh');
await enqueueEditorialBacklog(env,2);assert.equal(sent.length,3);assert.equal(sent[2].developmentIds[0],3);
sqlite.prepare('UPDATE developments SET editorial_started_at=datetime(\'now\') WHERE id=1').run();assert.equal((await processEditorialJob(env,sent[0])).status,'stale-dispatch');
sqlite.exec(`INSERT INTO developments(id,updated_at) VALUES(5,'2026-05-01')`);await assert.rejects(enqueueEditorialBacklog({...env,EDITORIAL_QUEUE:{send:async()=>{throw Error('queue unavailable')}}}),/queue unavailable/);assert.equal(sqlite.prepare('SELECT editorial_pending p FROM developments WHERE id=5').get().p,1);
const {validateRecord}=await moduleAt('shared/records.ts');const record={id:'example',slug:'example',kind:'observation',title:'Example',description:'Validation only',topics:[],places:[],sources:[{url:'https://example.com',publisher:'Example'}],libraryIds:[],relations:[],observations:[],status:'documented'};validateRecord(record);assert.throws(()=>validateRecord({...record,sources:[]}));assert.throws(()=>validateRecord({...record,observations:[{value:1}]}));
sqlite.close();console.log('Passed: expired lease recovery, oldest-first fairness, per-story dispatch, duplicate delivery, queue failure release, record provenance and observation validation.');
// Exercise publication SQL as a transaction; an obsolete lease must write nothing.
const {readFile,readdir}=await import('node:fs/promises');
const publicationDb=new DatabaseSync(':memory:');
for(const name of (await readdir('services/watch-engine/migrations')).filter(x=>x.endsWith('.sql')).sort())publicationDb.exec(await readFile('services/watch-engine/migrations/'+name,'utf8'));
const publicationSource=(await readFile('services/watch-engine/src/cluster/editorial.ts','utf8')).replace('async function finalize(', 'export async function finalize(');
const compiled=await build({stdin:{contents:publicationSource,resolveDir:process.cwd()+'/services/watch-engine/src/cluster',loader:'ts'},bundle:true,write:false,format:'esm',platform:'node'});
const {finalize}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const adapter={prepare(sql){let args=[];return {bind(...a){args=a;return this},async first(){return publicationDb.prepare(sql).get(...args)},async all(){return {results:publicationDb.prepare(sql).all(...args)}},async run(){return {meta:{changes:Number(publicationDb.prepare(sql).run(...args).changes)}}}}},async batch(statements){publicationDb.exec('BEGIN');try{const result=[];for(const stmt of statements)result.push(await stmt.run());publicationDb.exec('COMMIT');return result}catch(e){publicationDb.exec('ROLLBACK');throw e}}};
publicationDb.exec("INSERT INTO developments(id,title_en,status,editorial_dispatch_id,updated_at) VALUES(20,'Test','held','new-lease',datetime('now'))");
const draft={title_en:'A working visit',title_id:'Kunjungan kerja',summary_en:'A visit was reported.',summary_id:'Kunjungan dilaporkan.',key_points_en:[],key_points_id:[],what_changed_en:'',what_changed_id:'',common_ground:[],source_notes:[],places:[],topics:[]};
assert.equal((await finalize({DB:adapter,AUTO_PUBLISH:'true'},20,{},draft,false,'old-lease')).status,'stale-dispatch');
assert.equal(publicationDb.prepare('SELECT COUNT(*) n FROM development_syntheses').get().n,0);
assert.equal((await finalize({DB:adapter,AUTO_PUBLISH:'true'},20,{},draft,false,'new-lease')).status,'published');
assert.equal(publicationDb.prepare('SELECT COUNT(*) n FROM development_syntheses').get().n,1);
assert.ok(publicationDb.prepare('SELECT last_published_at FROM developments WHERE id=20').get().last_published_at);
publicationDb.close();console.log('Passed: atomic publication rejects stale leases without recording a synthesis.');
