import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {parseHTML} from 'linkedom';
import vm from 'node:vm';
const bundle=async path=>{const result=await build({entryPoints:[path],bundle:true,write:false,format:'esm',platform:'node'});return import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'))};
const {matchesFollowingEvidence}=await bundle('shared/following.ts');
assert.equal(matchesFollowingEvidence('mining-raja-ampat',['School opening in Raja Ampat','Mining permits in Sulawesi']),false);
assert.equal(matchesFollowingEvidence('mining-raja-ampat',['Nickel mining permits in Raja Ampat']),true);
assert.equal(matchesFollowingEvidence('south-papua-food-energy-estate',['Hospital visit in Merauke']),false);
assert.equal(matchesFollowingEvidence('south-papua-food-energy-estate',['Food estate project in Merauke']),true);
const runScript=async(path,html,fetch,reduce=false)=>{
 const {document,window}=parseHTML(html);let tick;
 const root=document.querySelector('[data-following-ticker]');if(root){const match=root.matches.bind(root);root.matches=s=>s===':hover'?false:match(s)}
 const code=(await readFile(path,'utf8')).split('<script>')[1].split('</script>')[0];
 const r=await build({stdin:{contents:code,resolveDir:process.cwd()+'/'+path.split('/').slice(0,-1).join('/'),loader:'ts'},bundle:true,write:false,format:'iife',platform:'browser'});
 const context={document,window,fetch,AbortSignal,URL,Date,console,matchMedia:()=>({matches:reduce,addEventListener(){}}),setTimeout,clearTimeout,clearInterval(){tick=undefined}};
 window.setInterval=fn=>{tick=fn;return 1};vm.runInNewContext(r.outputFiles[0].text,context);await new Promise(r=>setTimeout(r,20));return {document,tick:()=>tick?.()};
};
const home=await readFile('dist/index.html','utf8');
const requests=[];const article={id:1,title:{en:'Current reporting is available'},summary:{en:'Source summary'},story_url:'/story/?id=1',latest_report_at:'2026-09-22T00:00:00Z'};
const rendered=await runScript('src/views/HomeView.astro',home,async url=>{requests.push(url);if(url.includes('following'))throw Error('Following unavailable');return {ok:true,headers:{get:()=> 'application/json'},json:async()=>({items:[article]})}});
assert.equal(rendered.document.querySelector('[data-home-current-title]').textContent,article.title.en);assert.equal(rendered.document.querySelector('[data-home-current]').inert,false);assert.ok(!requests.some(x=>x.includes('following')));
assert.ok(home.indexOf('data-home-issues')>home.indexOf('data-home-current'));assert.ok(!home.includes('data-home-following-feature'));
const entries=[{slug:'freeport-mimika',title:{en:'Freeport and Mimika'},development:{id:1,title_en:'First report',story_url:'/story/?id=1',latest_report_at:'2026-09-22T10:00:00Z'}},{slug:'mining-raja-ampat',title:{en:'Mining in Raja Ampat'},development:{id:2,title_en:'Second report',story_url:'/story/?id=2',latest_report_at:'2026-09-21T10:00:00Z'}}];
const ticker=await runScript('src/components/FollowingTicker.astro',home,async()=>({ok:true,headers:{get:()=> 'application/json'},json:async()=>({items:entries})}));
assert.equal(ticker.document.querySelector('[data-update-title]').textContent,'First report');const colour=ticker.document.querySelector('[data-following-ticker]').style.getPropertyValue('--wash-0');
ticker.document.querySelector('[data-update-next]').click();assert.equal(ticker.document.querySelector('[data-update-title]').textContent,'Second report');assert.notEqual(ticker.document.querySelector('[data-following-ticker]').style.getPropertyValue('--wash-0'),colour);
ticker.document.querySelector('[data-update-pause]').click();assert.equal(ticker.document.querySelector('[data-update-pause]').getAttribute('aria-pressed'),'true');
const still=await runScript('src/components/FollowingTicker.astro',home,async()=>({ok:true,headers:{get:()=> 'application/json'},json:async()=>({items:entries})}),true);assert.equal(still.document.querySelector('[data-update-pause]').getAttribute('aria-pressed'),'true');
const data=await readFile('dist/data/index.html','utf8');assert.ok(data.includes('budget-comparison'));assert.ok(data.includes('data-mbg-map'));assert.ok(!data.includes('Inspect the Atlas'));assert.ok(!data.includes('Measured change'));assert.ok(data.includes('ice-ring'));
console.log('Passed: article-level case evidence, independent homepage News, rotating headline colours and pause/reduced motion, restored map and purposeful chart markup.');
const {DatabaseSync}=await import('node:sqlite');
const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE dossiers(slug TEXT,title_en TEXT,title_id TEXT,active INTEGER);CREATE TABLE developments(id INTEGER,status TEXT,title_en TEXT,title_id TEXT);CREATE TABLE development_issues(development_id INTEGER,issue_slug TEXT);CREATE TABLE development_articles(development_id INTEGER,article_id INTEGER);CREATE TABLE articles(id INTEGER,title TEXT,summary TEXT,published_at TEXT);INSERT INTO dossiers VALUES('mining-raja-ampat','Mining in Raja Ampat','Pertambangan Raja Ampat',1);INSERT INTO developments VALUES(1,'published','Mixed cluster',''),(2,'published','Mining report',''),(3,'held','Held report','');INSERT INTO development_issues VALUES(1,'mining-raja-ampat'),(2,'mining-raja-ampat'),(3,'mining-raja-ampat');INSERT INTO development_articles VALUES(1,1),(1,2),(2,3),(3,4);INSERT INTO articles VALUES(1,'School opening in Raja Ampat','',datetime('now')),(2,'Mining permits in Sulawesi','',datetime('now')),(3,'Nickel mining permits in Raja Ampat','',datetime('now','-1 hour')),(4,'Mining in Raja Ampat','',datetime('now'));`);
const source=await readFile('services/watch-engine/src/index.ts','utf8');const followingCode=source.slice(source.indexOf('async function following(env'),source.indexOf('async function emerging'));
const built=await build({stdin:{contents:`import {followingTickerSlugs,matchesFollowingEvidence} from './shared/following';const parseArray=v=>JSON.parse(v||'[]');export ${followingCode}`,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,platform:'node',format:'esm'});
const {following}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const DB={prepare(sql){let args=[];return{bind(...values){args=values;return this},async first(){return db.prepare(sql).get(...args)},async all(){return{results:db.prepare(sql).all(...args)}}}}};
const result=await following({DB});assert.equal(result.items.length,1);assert.equal(result.items[0].development.id,2);db.close();console.log('Passed: Following endpoint excludes held stories and mixed-article false matches using real SQLite queries.');
