import { embedText } from './embedding';import { runChat } from './llm';
const arr=(value:any)=>{try{return JSON.parse(String(value||'[]')) as string[]}catch{return[]}};
export async function answerQuestion(env:any,query:string,locale:'en'|'pmy'){
  const vector=await embedText(env,query);const nearest:any=await env.ARTICLE_INDEX.query(vector,{topK:10,returnMetadata:'all'});const ids=(nearest.matches||[]).map((m:any)=>Number(m.id)).filter(Boolean);let articles:any[]=[];
  if(ids.length){const marks=ids.map(()=>'?').join(',');const rows:any=await env.DB.prepare(`SELECT a.id,a.title,a.summary,a.canonical_url,a.published_at,p.name publisher,p.role,sp.summary packet_summary,sp.key_points_json,sp.what_changed,sp.places_json,sp.organizations_json,da.development_id FROM articles a JOIN publishers p ON p.id=a.publisher_id LEFT JOIN story_packets sp ON sp.article_id=a.id LEFT JOIN development_articles da ON da.article_id=a.id WHERE a.id IN (${marks})`).bind(...ids).all();articles=rows.results||[]}
  const devIds=[...new Set(articles.map(a=>Number(a.development_id)).filter(Boolean))].slice(0,5);let developments:any[]=[];if(devIds.length){const marks=devIds.map(()=>'?').join(',');const rows:any=await env.DB.prepare(`SELECT d.id,d.title_en,d.summary_en,d.issue_slug,ds.what_changed,ds.common_ground_json,ds.places_json,ds.topics_json FROM developments d LEFT JOIN development_syntheses ds ON ds.id=(SELECT id FROM development_syntheses WHERE development_id=d.id ORDER BY created_at DESC LIMIT 1) WHERE d.id IN (${marks})`).bind(...devIds).all();developments=rows.results||[]}
  const resourceRows:any=await env.DB.prepare(`SELECT title,source_url,publisher_id,kind,description,tags_json FROM resource_candidates WHERE status='published' AND (title LIKE ? OR description LIKE ? OR tags_json LIKE ?) LIMIT 5`).bind(`%${query.slice(0,60)}%`,`%${query.slice(0,60)}%`,`%${query.slice(0,40)}%`).all();
  const evidence:any[]=[];for(const d of developments)evidence.push({kind:'development',title:d.title_en,url:`/story/?id=${d.id}`,publisher:'West Papua Watch synthesis',text:`${d.summary_en||''}\nWhat changed: ${d.what_changed||''}\nCommon ground: ${arr(d.common_ground_json).join('; ')}`});for(const a of articles.slice(0,7))evidence.push({kind:'reporting',title:a.title,url:a.canonical_url,publisher:a.publisher,text:`${a.packet_summary||a.summary||''}\nKey points: ${arr(a.key_points_json).join('; ')}\nWhat changed: ${a.what_changed||''}`});for(const r of resourceRows.results||[])evidence.push({kind:'resource',title:r.title,url:r.source_url,publisher:r.publisher_id,text:`${r.kind}: ${r.description||''}\nTags: ${arr(r.tags_json).join(', ')}`});
  const sources=evidence.slice(0,10);if(!sources.length)return {answer:locale==='pmy'?'Belum ada sumber yang cukup di indeks Watch untuk jawab itu.':'The Watch index does not yet contain enough material to answer that.',sources:[]};
  const context=sources.map((s,i)=>`[S${i+1}] ${s.kind.toUpperCase()} · ${s.title}\nPublisher: ${s.publisher}\n${s.text}\nURL: ${s.url}`).join('\n\n');const language=locale==='pmy'?'clear everyday Papuan Malay (Melayu Papua)':'English';
  const answer=await runChat(env,[{role:'system',content:`You answer for West Papua Watch from retrieved material only. Use ${language}. Be concise, calm and specific. Cite factual claims inline as [S1], [S2]. Prefer multi-source Development syntheses for event-level answers, then use individual reporting for provenance. Distinguish reporting, civil-society claims, public/state media and official records by attribution. If evidence is insufficient or sources disagree, say so. Never invent a source, quotation or certainty.`},{role:'user',content:`Question: ${query}\n\nRetrieved material:\n${context}`}],'ask',850);
  return {answer,sources:sources.map(({kind,title,url,publisher})=>({kind,title,url,publisher}))};
}
