import { tryEmbedText } from './embedding';
import { runChat } from './llm';
import { searchArticleFts,searchDevelopmentFts } from './search';
const arr=(value:any)=>{try{const x=JSON.parse(String(value||'[]'));return Array.isArray(x)?x.map(String):[]}catch{return[]}};

export async function answerQuestion(env:any,query:string,locale:'en'|'pmy'){
  const articleIds=new Set<number>(await searchArticleFts(env,query,12));const developmentIds=new Set<number>(await searchDevelopmentFts(env,query,8));
  const vector=await tryEmbedText(env,query);if(vector){try{const nearest:any=await env.ARTICLE_INDEX.query(vector,{topK:12,returnMetadata:'all'});for(const m of nearest.matches||[]){const id=String(m.id);if(id.startsWith('dev:'))developmentIds.add(Number(id.slice(4)));else{const n=Number(id);if(Number.isFinite(n))articleIds.add(n)}}}catch(e){console.warn('Ask Vectorize enhancement unavailable',e)}}
  let articles:any[]=[];const ids=[...articleIds].filter(Number.isFinite).slice(0,12);if(ids.length){const marks=ids.map(()=>'?').join(',');const rows:any=await env.DB.prepare(`SELECT a.id,a.title,a.summary,a.canonical_url,a.published_at,p.name publisher,p.role,sp.summary packet_summary,sp.key_points_json,sp.what_changed,sp.places_json,sp.organizations_json,da.development_id FROM articles a JOIN publishers p ON p.id=a.publisher_id LEFT JOIN story_packets sp ON sp.article_id=a.id LEFT JOIN development_articles da ON da.article_id=a.id WHERE a.id IN (${marks})`).bind(...ids).all();articles=rows.results||[];for(const a of articles)if(a.development_id)developmentIds.add(Number(a.development_id))}
  let developments:any[]=[];const devIds=[...developmentIds].filter(Number.isFinite).slice(0,8);if(devIds.length){const marks=devIds.map(()=>'?').join(',');const rows:any=await env.DB.prepare(`SELECT d.id,d.title_en,d.title_id,d.summary_en,d.summary_id,d.issue_slug,ds.what_changed,ds.what_changed_id,ds.common_ground_json,ds.places_json,ds.topics_json FROM developments d LEFT JOIN development_syntheses ds ON ds.id=(SELECT id FROM development_syntheses WHERE development_id=d.id ORDER BY created_at DESC LIMIT 1) WHERE d.id IN (${marks})`).bind(...devIds).all();developments=rows.results||[]}
  const resourceRows:any=await env.DB.prepare(`SELECT title,source_url,publisher_id,kind,description,tags_json FROM resource_candidates WHERE status='published' AND (title LIKE ? OR description LIKE ? OR tags_json LIKE ?) LIMIT 5`).bind(`%${query.slice(0,60)}%`,`%${query.slice(0,60)}%`,`%${query.slice(0,40)}%`).all();
  const useId=locale==='pmy',evidence:any[]=[];for(const d of developments)evidence.push({kind:'development',title:useId?(d.title_id||d.title_en):d.title_en,url:`/story/?id=${d.id}`,publisher:'West Papua Watch synthesis',text:`${useId?(d.summary_id||d.summary_en):d.summary_en||''}\nWhat changed: ${useId?(d.what_changed_id||d.what_changed):d.what_changed||''}\nCommon ground: ${arr(d.common_ground_json).join('; ')}`});for(const a of articles.slice(0,8))evidence.push({kind:'reporting',title:a.title,url:a.canonical_url,publisher:a.publisher,text:`${a.packet_summary||a.summary||''}\nKey points: ${arr(a.key_points_json).join('; ')}\nWhat changed: ${a.what_changed||''}`});for(const r of resourceRows.results||[])evidence.push({kind:'resource',title:r.title,url:r.source_url,publisher:r.publisher_id,text:`${r.kind}: ${r.description||''}\nTags: ${arr(r.tags_json).join(', ')}`});
  const sources=evidence.slice(0,12);if(!sources.length)return {answer:useId?'Indeks Watch belum punya cukup bahan untuk menjawab pertanyaan itu.':'The Watch index does not yet contain enough material to answer that.',sources:[],language:useId?'id':'en'};
  const context=sources.map((s,i)=>`[S${i+1}] ${s.kind.toUpperCase()} · ${s.title}\nPublisher: ${s.publisher}\n${s.text}\nURL: ${s.url}`).join('\n\n'),language=useId?'Bahasa Indonesia. Do not imitate or generate Papuan Malay':'English';const answer=await runChat(env,[{role:'system',content:`You answer for West Papua Watch from retrieved material only. Use ${language}. Be concise, calm and specific. Cite factual claims inline as [S1], [S2]. Prefer multi-source Development syntheses for event-level answers, then individual reporting for provenance. Distinguish reporting, civil-society claims, public/state media and official records by attribution. If evidence is insufficient or sources disagree, say so.`},{role:'user',content:`Question: ${query}\n\nRetrieved material:\n${context}`}],'ask',850);return {answer,sources:sources.map(({kind,title,url,publisher})=>({kind,title,url,publisher})),language:useId?'id':'en'};
}
