import { runJson } from './llm';
import { searchDevelopmentFts } from './search';

const schemaItem={type:'object',properties:{group_key:{type:'string'},coherent:{type:'boolean'},title_en:{type:'string'},title_id:{type:'string'},summary_en:{type:'string'},summary_id:{type:'string'},domain_hint:{type:'string'},reason:{type:'string'}},required:['group_key','coherent','title_en','title_id','summary_en','summary_id','domain_hint','reason'],additionalProperties:false};
const schema={type:'object',properties:{items:{type:'array',items:schemaItem}},required:['items'],additionalProperties:false};
const slugify=(s:string)=>s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||`emerging-${Date.now()}`;

export async function detectEmergingIssues(env:any,limit=24){
  const rows:any=await env.DB.prepare(`SELECT d.id,d.title_en,d.title_id,d.summary_en,d.summary_id,d.event_signature,d.first_seen_at,d.updated_at FROM developments d WHERE d.status='published' AND d.updated_at>=datetime('now','-90 days') ORDER BY d.updated_at DESC LIMIT ?`).bind(limit).all();
  const byId=new Map((rows.results||[]).map((x:any)=>[Number(x.id),x]));const groups:any[]=[];const seen=new Set<string>();
  for(const seed of rows.results||[]){const ids=[Number(seed.id),...(await searchDevelopmentFts(env,`${seed.event_signature||''} ${seed.title_id||seed.title_en}`,8))];const uniq=[...new Set(ids)].filter(id=>byId.has(id)).slice(0,8);if(uniq.length<3)continue;const group=uniq.map(id=>byId.get(id));const times=group.map((x:any)=>+new Date(x.first_seen_at||x.updated_at)).filter(Number.isFinite);if(!times.length||((Math.max(...times)-Math.min(...times))/864e5)<14)continue;const key=uniq.sort((a,b)=>a-b).join(',');if(seen.has(key))continue;seen.add(key);groups.push({key,group});if(groups.length>=6)break}
  if(!groups.length)return {checked:(rows.results||[]).length,upserted:0};
  const prompt=groups.map(g=>`GROUP ${g.key}\n${g.group.map((x:any)=>`#${x.id} ${x.title_id||x.title_en}\n${x.summary_id||x.summary_en}`).join('\n\n')}`).join('\n\n================\n\n');let output:any;
  try{output=await runJson(env,[{role:'system',content:'Judge each GROUP independently. A coherent emerging issue is a persistent real-world storyline made of distinct events across time, not merely a broad theme. Write restrained publication-ready English and Bahasa Indonesia. Never mix evidence between group keys.'},{role:'user',content:prompt}],schema,'fast',2200)}catch(e){console.warn('daily emerging issue batch skipped',e);return {checked:(rows.results||[]).length,upserted:0,error:'model-unavailable'}}
  const verdicts=new Map((output.items||[]).map((x:any)=>[String(x.group_key),x]));let upserted=0;
  for(const g of groups){const o:any=verdicts.get(g.key);if(o?.coherent!==true||!String(o.title_en||'').trim())continue;const times=g.group.map((x:any)=>+new Date(x.first_seen_at||x.updated_at)),slug=slugify(String(o.title_en)),now=new Date().toISOString(),first=new Date(Math.min(...times)).toISOString(),last=new Date(Math.max(...times)).toISOString();const sourceRows:any=await env.DB.prepare(`SELECT COUNT(DISTINCT CASE WHEN a.syndicated_from_article_id IS NULL THEN a.publisher_id END) n FROM development_articles da JOIN articles a ON a.id=da.article_id WHERE da.development_id IN (${g.group.map(()=>'?').join(',')})`).bind(...g.group.map((x:any)=>x.id)).first();const sources=Number(sourceRows?.n||0);if(sources<2)continue;await env.DB.prepare(`INSERT INTO emerging_issues(slug,title,title_id,summary,summary_id,domain_hint,status,first_seen_at,last_seen_at,development_count,source_count,created_at,updated_at) VALUES(?,?,?,?,?,?,'emerging',?,?,?,?,?,?) ON CONFLICT(slug) DO UPDATE SET title=excluded.title,title_id=excluded.title_id,summary=excluded.summary,summary_id=excluded.summary_id,domain_hint=excluded.domain_hint,last_seen_at=excluded.last_seen_at,development_count=excluded.development_count,source_count=excluded.source_count,updated_at=excluded.updated_at`).bind(slug,String(o.title_en).slice(0,300),String(o.title_id||o.title_en).slice(0,300),String(o.summary_en||'').slice(0,1400),String(o.summary_id||o.summary_en||'').slice(0,1400),String(o.domain_hint||'').slice(0,120),first,last,g.group.length,sources,now,now).run();const issue:any=await env.DB.prepare(`SELECT id FROM emerging_issues WHERE slug=?`).bind(slug).first();if(issue?.id)for(const d of g.group)await env.DB.prepare(`INSERT OR REPLACE INTO emerging_issue_developments(emerging_issue_id,development_id,score) VALUES(?,?,1)`).bind(issue.id,d.id).run();upserted++}
  return {checked:(rows.results||[]).length,upserted};
}
