import { NewsCycleWorkflow } from './workflow';import { processArticle } from './ingest/process';import { answerQuestion } from './ask';
export { NewsCycleWorkflow };
const json=(data:any,status=200,cache='no-store')=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':cache,'x-content-type-options':'nosniff'}});
async function current(env:any){
  const rows:any=await env.DB.prepare(`SELECT d.id,d.issue_slug,d.title_en,d.title_pmy,d.summary_en,d.summary_pmy,d.updated_at,COUNT(DISTINCT CASE WHEN a.syndicated_from_article_id IS NULL THEN a.publisher_id END) source_count FROM developments d JOIN development_articles da ON da.development_id=d.id JOIN articles a ON a.id=da.article_id WHERE d.status='published' GROUP BY d.id ORDER BY d.updated_at DESC LIMIT 12`).all();const items=[];
  for(const d of rows.results||[]){const image:any=await env.DB.prepare(`SELECT ic.url,ic.source_url,ic.credit,ic.caption,ic.rights_status,p.name publisher FROM image_candidates ic JOIN articles a ON a.id=ic.article_id JOIN publishers p ON p.id=a.publisher_id JOIN development_articles da ON da.article_id=ic.article_id WHERE da.development_id=? AND (ic.rights_status IN ('approved','attributed_external') OR ?='true') ORDER BY CASE ic.rights_status WHEN 'approved' THEN 0 ELSE 1 END,ic.id DESC LIMIT 1`).bind(d.id,env.ALLOW_EXTERNAL_IMAGES||'false').first();const article:any=await env.DB.prepare(`SELECT a.title,p.role,p.name publisher,a.publisher_id FROM development_articles da JOIN articles a ON a.id=da.article_id JOIN publishers p ON p.id=a.publisher_id WHERE da.development_id=? ORDER BY COALESCE(a.published_at,a.fetched_at) DESC LIMIT 1`).bind(d.id).first();items.push({id:d.id,story_url:`/story/?id=${d.id}`,issue_slug:d.issue_slug,title:{en:d.title_en,pmy:d.title_pmy||d.title_en},summary:{en:d.summary_en,pmy:d.summary_pmy||d.summary_en},category:d.issue_slug?.includes('raja')||d.issue_slug?.includes('sentani')?'Environment':d.issue_slug?.includes('food')?'Land':'Current',place:d.issue_slug?.includes('raja')?'Raja Ampat':d.issue_slug?.includes('sentani')?'Lake Sentani':d.issue_slug?.includes('south-papua')?'South Papua':'West Papua',updated_at:d.updated_at,source_count:d.source_count,latest_source:article?{publisher_id:article.publisher_id,publisher:article.publisher,role:article.role}:null,image:image?{url:image.url,source_url:image.source_url,credit:image.credit||image.publisher,caption:image.caption,rights_status:image.rights_status}:null})}return items;
}
async function development(env:any,id:number){const d:any=await env.DB.prepare(`SELECT * FROM developments WHERE id=? AND status='published'`).bind(id).first();if(!d)return null;const synthesis:any=await env.DB.prepare(`SELECT * FROM development_syntheses WHERE development_id=? ORDER BY created_at DESC LIMIT 1`).bind(id).first();const rows:any=await env.DB.prepare(`SELECT a.id,a.title,a.summary,a.canonical_url,a.published_at,a.language,p.id publisher_id,p.name publisher,p.role,sp.summary packet_summary,sp.key_points_json,sp.what_changed,sp.places_json,sp.people_json,sp.organizations_json,sp.topics_json,ic.url image_url,ic.source_url image_source_url,ic.credit image_credit FROM development_articles da JOIN articles a ON a.id=da.article_id JOIN publishers p ON p.id=a.publisher_id LEFT JOIN story_packets sp ON sp.article_id=a.id LEFT JOIN image_candidates ic ON ic.id=(SELECT id FROM image_candidates WHERE article_id=a.id ORDER BY id DESC LIMIT 1) WHERE da.development_id=? ORDER BY COALESCE(a.published_at,a.fetched_at) DESC`).bind(id).all();return {development:d,synthesis,articles:rows.results||[]}}
async function resources(env:any,url:URL){const status=url.searchParams.get('status')==='candidate'?'candidate':'published';const rows:any=await env.DB.prepare(`SELECT * FROM resource_candidates WHERE status=? ORDER BY COALESCE(updated_at,created_at) DESC LIMIT 100`).bind(status).all();return rows.results||[]}
export default {
  async fetch(request:any,env:any){const url=new URL(request.url);
    if(url.pathname==='/health')return json({ok:true,service:'westpapua-watch-engine',bindings:{db:!!env.DB,archive:!!env.ARCHIVE,vectorize:!!env.ARTICLE_INDEX,ai:!!env.AI,browser:!!env.BROWSER,queue:!!env.INGEST_QUEUE,workflow:!!env.NEWS_CYCLE},optional:{firecrawl:!!env.FIRECRAWL_API_KEY,aiGateway:!!(env.AI_GATEWAY_BASE&&env.AI_GATEWAY_TOKEN)}});
    if(url.pathname==='/current'&&request.method==='GET')return json({items:await current(env)},200,'public, max-age=60, stale-while-revalidate=180');
    const devMatch=url.pathname.match(/^\/development\/(\d+)$/);if(devMatch&&request.method==='GET'){const item=await development(env,Number(devMatch[1]));return item?json(item):json({error:'Not found'},404)}
    if(url.pathname==='/resources'&&request.method==='GET')return json({items:await resources(env,url)});
    if(url.pathname==='/ask'&&request.method==='POST'){let body:any;try{body=await request.json()}catch{return json({error:'Invalid JSON'},400)}const query=String(body?.query||'').trim();if(query.length<2||query.length>500)return json({error:'Question must be between 2 and 500 characters.'},400);try{return json(await answerQuestion(env,query,body?.locale==='pmy'?'pmy':'en'))}catch(error){console.error('ask failed',error);return json({error:'The Watch answer service is temporarily unavailable.'},502)}}
    if(url.pathname==='/review/candidates'&&request.method==='GET'){const rows:any=await env.DB.prepare(`SELECT d.*,COUNT(da.article_id) article_count,COUNT(DISTINCT CASE WHEN a.syndicated_from_article_id IS NULL AND p.role NOT IN ('state_media','official_record','state_public_media') THEN a.publisher_id END) independent_source_count FROM developments d LEFT JOIN development_articles da ON da.development_id=d.id LEFT JOIN articles a ON a.id=da.article_id LEFT JOIN publishers p ON p.id=a.publisher_id WHERE d.status='candidate' GROUP BY d.id ORDER BY d.updated_at DESC LIMIT 50`).all();return json({items:rows.results||[]})}
    if(url.pathname==='/review/resources'&&request.method==='GET')return json({items:await resources(env,new URL('https://watch.internal/resources?status=candidate'))});
    if(url.pathname==='/review/issue-deltas'&&request.method==='GET'){const rows:any=await env.DB.prepare(`SELECT * FROM issue_delta_candidates WHERE status='candidate' ORDER BY created_at DESC LIMIT 80`).all();return json({items:rows.results||[]})}
    if(url.pathname==='/run'&&request.method==='POST'){const instance=await env.NEWS_CYCLE.create({params:{reason:'manual'}});return json({id:instance.id},202)}return json({error:'Not found'},404)
  },
  async queue(batch:any,env:any){for(const message of batch.messages){try{await processArticle(env,message.body);message.ack()}catch(error){console.error('ingest failed',message.body?.url,error);message.retry()}}}
};
