import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root=process.cwd();
const areas={history:{file:'content/history.json',list:'chapters',id:'id'},events:{file:'content/events.json',list:'events',id:'id'},exhibition:{file:'content/exhibition.json',list:'items',id:'slug'},sources:{file:'content/news-sources.json',list:null,id:'id'}};
const usage=()=>{console.log(`Watch Steward content tool\n\nRead:\n  node scripts/steward-content.mjs list <history|events|exhibition|sources>\n  node scripts/steward-content.mjs show <area> <id>\n\nSafe edits (never delete records):\n  node scripts/steward-content.mjs set <area> <id> <field.path> <value>\n  node scripts/steward-content.mjs add <history|events|exhibition|sources> '<json object>'\n  node scripts/steward-content.mjs add-resource <source-id>\n  node scripts/steward-content.mjs hide <history|events|exhibition> <id> <true|false>\n  node scripts/steward-content.mjs source <id> <enable|disable>\n  node scripts/steward-content.mjs set-ui <field.path> <value>\n\nValues are strings except true/false/numbers, which are parsed.`)};
const parseValue=(raw)=>raw==='true'?true:raw==='false'?false:/^-?\d+(\.\d+)?$/.test(raw)?Number(raw):raw;
const load=(rel)=>JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'));const save=(rel,data)=>fs.writeFileSync(path.join(root,rel),JSON.stringify(data,null,2)+'\n');
const getArea=(name)=>{const area=areas[name];if(!area)throw new Error(`Unknown area ${name}`);const data=load(area.file);const list=area.list?data[area.list]:data;return {area,data,list}};
const setPath=(object,field,value)=>{const parts=field.split('.').filter(Boolean);if(!parts.length)throw new Error('Field path required');let cursor=object;for(const key of parts.slice(0,-1)){if(!cursor[key]||typeof cursor[key]!=='object'||Array.isArray(cursor[key]))throw new Error(`Unknown field path ${field}`);cursor=cursor[key]}const key=parts.at(-1);if(!(key in cursor))throw new Error(`Unknown field ${field}`);cursor[key]=value};
const validateOrRestore=(file,before)=>{const check=spawnSync(process.execPath,['scripts/check-content.mjs'],{cwd:root,stdio:'inherit'});if(check.status!==0){fs.writeFileSync(path.join(root,file),before);throw new Error('Validation failed; edit rolled back')}};
const [cmd,a,b,c,...rest]=process.argv.slice(2);if(!cmd){usage();process.exit(0)}
try{
  if(cmd==='list'){const {list}=getArea(a);console.log(JSON.stringify(list,null,2));process.exit(0)}
  if(cmd==='show'){const {area,list}=getArea(a);const item=list.find(x=>x?.[area.id]===b);if(!item)throw new Error(`Unknown ${a} item ${b}`);console.log(JSON.stringify(item,null,2));process.exit(0)}
  if(cmd==='add'){const {area,data,list}=getArea(a);const raw=[b,c,...rest].filter(x=>x!==undefined).join(' ');if(!raw)throw new Error('JSON object required');let item;try{item=JSON.parse(raw)}catch{throw new Error('add expects one JSON object')};if(!item||Array.isArray(item)||typeof item!=='object')throw new Error('add expects one JSON object');const before=fs.readFileSync(path.join(root,area.file),'utf8');list.push(item);save(area.file,data);validateOrRestore(area.file,before);console.log(`added ${a}:${item[area.id]||'new item'}`);process.exit(0)}
  if(cmd==='add-resource'){if(!a)throw new Error('source id required');const file='content/resources.json',data=load(file),before=fs.readFileSync(path.join(root,file),'utf8');if(data.resourceIds.includes(a)){console.log(`${a} already in resources`);process.exit(0)}data.resourceIds.push(a);save(file,data);validateOrRestore(file,before);console.log(`added resource ${a}`);process.exit(0)}
  if(cmd==='set'){const {area,data,list}=getArea(a);const item=list.find(x=>x?.[area.id]===b);if(!item)throw new Error(`Unknown ${a} item ${b}`);if(!c)throw new Error('Field path required');if(!rest.length)throw new Error('Value required');const raw=rest.join(' ');const before=fs.readFileSync(path.join(root,area.file),'utf8');setPath(item,c,parseValue(raw));save(area.file,data);validateOrRestore(area.file,before);console.log(`updated ${a}:${b} ${c}`);process.exit(0)}
  if(cmd==='hide'){if(a==='sources')throw new Error('Use source enable|disable');const {area,data,list}=getArea(a);const item=list.find(x=>x?.[area.id]===b);if(!item)throw new Error(`Unknown ${a} item ${b}`);if(!['true','false'].includes(c))throw new Error('hide value must be true or false');const before=fs.readFileSync(path.join(root,area.file),'utf8');item.hidden=c==='true';save(area.file,data);validateOrRestore(area.file,before);console.log(`${a}:${b} hidden=${item.hidden}`);process.exit(0)}
  if(cmd==='source'){const {area,data,list}=getArea('sources');const item=list.find(x=>x?.id===a);if(!item)throw new Error(`Unknown source ${a}`);if(!['enable','disable'].includes(b))throw new Error('Use enable or disable');const before=fs.readFileSync(path.join(root,area.file),'utf8');item.enabled=b==='enable';save(area.file,data);validateOrRestore(area.file,before);console.log(`${a} enabled=${item.enabled}`);process.exit(0)}
  if(cmd==='set-ui'){const file='content/ui.json',data=load(file),before=fs.readFileSync(path.join(root,file),'utf8');const raw=[b,c,...rest].filter(x=>x!==undefined).join(' ');setPath(data,a,parseValue(raw));save(file,data);validateOrRestore(file,before);console.log(`updated ui ${a}`);process.exit(0)}
  usage();process.exit(2);
}catch(error){console.error(error.message);process.exit(1)}
