import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
type Item={title:string;url:string;summary?:string;source?:string;date?:string;coordinates?:[number,number]};
type Section='news'|'wiki'|'library';
const el=(id:string)=>document.getElementById(id)!;
let section:Section='news',map:maplibregl.Map|undefined,mapReady=false,requestId=0;
let points:GeoJSON.FeatureCollection={type:'FeatureCollection',features:[]};
const labels={news:['Perkembangan terbaru','Watch · ringkasan bersumber'],wiki:['Kenali tanah ini','Referensi · bukan wiki suntingan terbuka'],library:['Baca lebih jauh','Pustaka Watch']};
const colors={news:'#995736',wiki:'#557b68',library:'#77709c'};
function safeUrl(value:string){try{const u=new URL(value,location.origin);return ['https:','http:'].includes(u.protocol)?u.href:null}catch{return null}}
function render(items:Item[],target:HTMLElement){target.replaceChildren();for(const item of items){const href=safeUrl(item.url);if(!href||!item.title)continue;const row=document.createElement('article');row.className='content-row';const meta=document.createElement('div');meta.className='row-meta';meta.textContent=item.source||'Sumber publik';const a=document.createElement('a');a.href=href;const h=document.createElement('h3');h.textContent=item.title;a.append(h);row.append(meta,a);if(item.summary){const p=document.createElement('p');p.textContent=item.summary;row.append(p)}const footer=document.createElement('div');footer.className='row-footer';const d=item.date?new Date(item.date):null;footer.textContent=d&&!Number.isNaN(d.getTime())?d.toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'}):'Buka sumber ↗';row.append(footer);target.append(row)}}
async function load(url:string){const response=await fetch(url,{signal:AbortSignal.timeout(15000),credentials:'omit'});if(!response.ok)throw new Error('Sumber belum dapat dihubungi. Coba lagi sebentar.');const data=await response.json();if(data.error)throw new Error(data.error);if(!Array.isArray(data.items))throw new Error('Format data belum tersedia.');return Object.assign(data.items as Item[],{notice:data.snapshot?'Salinan sumber '+new Date(data.capturedAt).toLocaleString('id-ID')+' · sambungan langsung belum tersedia.':''})}
function retry(status:HTMLElement,action:()=>void,message:string){status.replaceChildren(document.createTextNode(message+' '));const button=document.createElement('button');button.className='retry-button';button.type='button';button.textContent='Coba lagi';button.onclick=action;status.append(button)}
async function forum(){el('forum-status').textContent='Menghubungkan percakapan…';try{const items=await load('/api/etnos/forum');render(items,el('forum-feed'));el('forum-status').textContent=(items as any).notice|| (items.length?'Percakapan publik dari PieFed. Bukan feed khusus komunitas Papua.':'Belum ada percakapan untuk ditampilkan.')}catch(e){retry(el('forum-status'),forum,e instanceof Error?e.message:'Percakapan belum tersedia.')}}
function updateMap(){if(!mapReady||!map)return;(map.getSource('context') as maplibregl.GeoJSONSource).setData(points);map.setPaintProperty('context-points','circle-color',colors[section]);el('map-legend').textContent=points.features.length?`${points.features.length} lokasi bersumber · ${labels[section][0]}`:'Tanpa titik lokasi pada bagian ini';}
function initMap(){if(map){requestAnimationFrame(()=>map?.resize());return}try{map=new maplibregl.Map({container:'explore-map',style:'https://tiles.openfreemap.org/styles/positron',center:[136,-4],zoom:4.5,attributionControl:{compact:true}});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('load',()=>{mapReady=true;el('explore-map').dataset.ready='true';map!.addSource('context',{type:'geojson',data:points});map!.addLayer({id:'context-points',type:'circle',source:'context',paint:{'circle-radius':6,'circle-color':colors[section],'circle-stroke-color':'#f5f2ea','circle-stroke-width':2}});updateMap()});map.on('error',()=>{el('map-legend').textContent='Sebagian peta belum tersedia. Daftar tetap dapat dibaca.'});map.on('click','context-points',event=>{const feature=event.features?.[0];if(!feature||feature.geometry.type!=='Point')return;const body=document.createElement('div');body.textContent=String(feature.properties?.title||'Lokasi bersumber');new maplibregl.Popup().setLngLat(feature.geometry.coordinates as [number,number]).setDOMContent(body).addTo(map!)});}catch{el('explore-map').textContent='Peta tidak tersedia pada perangkat ini. Semua bahan tetap tersedia di daftar.'}}
async function explore(){const id=++requestId;el('explore-section-title').textContent=labels[section][0];el('explore-provenance').textContent=labels[section][1];document.querySelectorAll<HTMLButtonElement>('[data-section]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.section===section)));el('explore-feed').replaceChildren();el('explore-status').textContent='Memuat bahan…';points={type:'FeatureCollection',features:[]};updateMap();try{const items=await load(`/api/etnos/explore?section=${section}`);if(id!==requestId)return;render(items,el('explore-feed'));points={type:'FeatureCollection',features:items.filter(i=>i.coordinates?.length===2&&i.coordinates.every(Number.isFinite)&&Math.abs(i.coordinates[0])<=180&&Math.abs(i.coordinates[1])<=90).map(i=>({type:'Feature',geometry:{type:'Point',coordinates:i.coordinates!},properties:{title:i.title}}))};updateMap();el('explore-status').textContent=(items as any).notice||(items.length?'':'Belum ada bahan pada bagian ini.')}catch(e){if(id!==requestId)return;retry(el('explore-status'),explore,e instanceof Error?e.message:'Bahan belum tersedia.')}}
function navigate(){const active=location.hash.startsWith('#explore')?'explore':'forum';el('forum-view').hidden=active!=='forum';el('explore-view').hidden=active!=='explore';document.querySelectorAll('[data-destination]').forEach(a=>{if((a as HTMLElement).dataset.destination===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(active==='explore'){const requested=location.hash.split('/')[1];section=['news','wiki','library'].includes(requested)?requested as Section:'news';initMap();explore()}}
document.querySelectorAll<HTMLButtonElement>('[data-section]').forEach(b=>b.onclick=()=>{location.hash=`explore/${b.dataset.section}`});window.addEventListener('hashchange',navigate);navigate();forum();
